# English Content Expansion for Weekly Star Tracker
# Massive vocabulary expansion for better variety

# English Vocabulary - Basic Level (200 words)
ENGLISH_VOCABULARY_BASIC = [
    # Animals (50 words)
    {"english": "dog", "german": "Hund", "category": "animals"},
    {"english": "cat", "german": "Katze", "category": "animals"},
    {"english": "mouse", "german": "Maus", "category": "animals"},
    {"english": "bird", "german": "Vogel", "category": "animals"},
    {"english": "fish", "german": "Fisch", "category": "animals"},
    {"english": "horse", "german": "Pferd", "category": "animals"},
    {"english": "cow", "german": "Kuh", "category": "animals"},
    {"english": "pig", "german": "Schwein", "category": "animals"},
    {"english": "sheep", "german": "Schaf", "category": "animals"},
    {"english": "goat", "german": "Ziege", "category": "animals"},
    {"english": "rabbit", "german": "Hase", "category": "animals"},
    {"english": "hamster", "german": "Hamster", "category": "animals"},
    {"english": "guinea pig", "german": "Meerschweinchen", "category": "animals"},
    {"english": "frog", "german": "Frosch", "category": "animals"},
    {"english": "snake", "german": "Schlange", "category": "animals"},
    {"english": "turtle", "german": "Schildkröte", "category": "animals"},
    {"english": "elephant", "german": "Elefant", "category": "animals"},
    {"english": "lion", "german": "Löwe", "category": "animals"},
    {"english": "tiger", "german": "Tiger", "category": "animals"},
    {"english": "bear", "german": "Bär", "category": "animals"},
    {"english": "monkey", "german": "Affe", "category": "animals"},
    {"english": "giraffe", "german": "Giraffe", "category": "animals"},
    {"english": "zebra", "german": "Zebra", "category": "animals"},
    {"english": "penguin", "german": "Pinguin", "category": "animals"},
    {"english": "polar bear", "german": "Eisbär", "category": "animals"},
    {"english": "seal", "german": "Seehund", "category": "animals"},
    {"english": "dolphin", "german": "Delfin", "category": "animals"},
    {"english": "whale", "german": "Wal", "category": "animals"},
    {"english": "shark", "german": "Hai", "category": "animals"},
    {"english": "starfish", "german": "Seestern", "category": "animals"},
    {"english": "crab", "german": "Krabbe", "category": "animals"},
    {"english": "butterfly", "german": "Schmetterling", "category": "animals"},
    {"english": "bee", "german": "Biene", "category": "animals"},
    {"english": "spider", "german": "Spinne", "category": "animals"},
    {"english": "ant", "german": "Ameise", "category": "animals"},
    {"english": "fly", "german": "Fliege", "category": "animals"},
    {"english": "mosquito", "german": "Mücke", "category": "animals"},
    {"english": "beetle", "german": "Käfer", "category": "animals"},
    {"english": "snail", "german": "Schnecke", "category": "animals"},
    {"english": "worm", "german": "Wurm", "category": "animals"},
    {"english": "duck", "german": "Ente", "category": "animals"},
    {"english": "chicken", "german": "Huhn", "category": "animals"},
    {"english": "rooster", "german": "Hahn", "category": "animals"},
    {"english": "goose", "german": "Gans", "category": "animals"},
    {"english": "swan", "german": "Schwan", "category": "animals"},
    {"english": "owl", "german": "Eule", "category": "animals"},
    {"english": "eagle", "german": "Adler", "category": "animals"},
    {"english": "parrot", "german": "Papagei", "category": "animals"},
    {"english": "sparrow", "german": "Spatz", "category": "animals"},
    {"english": "robin", "german": "Rotkehlchen", "category": "animals"},

    # Food (50 words)
    {"english": "apple", "german": "Apfel", "category": "food"},
    {"english": "banana", "german": "Banane", "category": "food"},
    {"english": "orange", "german": "Orange", "category": "food"},
    {"english": "lemon", "german": "Zitrone", "category": "food"},
    {"english": "grape", "german": "Traube", "category": "food"},
    {"english": "strawberry", "german": "Erdbeere", "category": "food"},
    {"english": "cherry", "german": "Kirsche", "category": "food"},
    {"english": "peach", "german": "Pfirsich", "category": "food"},
    {"english": "pear", "german": "Birne", "category": "food"},
    {"english": "plum", "german": "Pflaume", "category": "food"},
    {"english": "bread", "german": "Brot", "category": "food"},
    {"english": "butter", "german": "Butter", "category": "food"},
    {"english": "cheese", "german": "Käse", "category": "food"},
    {"english": "milk", "german": "Milch", "category": "food"},
    {"english": "egg", "german": "Ei", "category": "food"},
    {"english": "meat", "german": "Fleisch", "category": "food"},
    {"english": "chicken", "german": "Hähnchen", "category": "food"},
    {"english": "fish", "german": "Fisch", "category": "food"},
    {"english": "rice", "german": "Reis", "category": "food"},
    {"english": "pasta", "german": "Nudeln", "category": "food"},
    {"english": "potato", "german": "Kartoffel", "category": "food"},
    {"english": "carrot", "german": "Karotte", "category": "food"},
    {"english": "tomato", "german": "Tomate", "category": "food"},
    {"english": "onion", "german": "Zwiebel", "category": "food"},
    {"english": "garlic", "german": "Knoblauch", "category": "food"},
    {"english": "cucumber", "german": "Gurke", "category": "food"},
    {"english": "lettuce", "german": "Salat", "category": "food"},
    {"english": "cabbage", "german": "Kohl", "category": "food"},
    {"english": "spinach", "german": "Spinat", "category": "food"},
    {"english": "broccoli", "german": "Brokkoli", "category": "food"},
    {"english": "corn", "german": "Mais", "category": "food"},
    {"english": "peas", "german": "Erbsen", "category": "food"},
    {"english": "beans", "german": "Bohnen", "category": "food"},
    {"english": "soup", "german": "Suppe", "category": "food"},
    {"english": "salad", "german": "Salat", "category": "food"},
    {"english": "cake", "german": "Kuchen", "category": "food"},
    {"english": "cookie", "german": "Keks", "category": "food"},
    {"english": "chocolate", "german": "Schokolade", "category": "food"},
    {"english": "candy", "german": "Bonbon", "category": "food"},
    {"english": "ice cream", "german": "Eis", "category": "food"},
    {"english": "water", "german": "Wasser", "category": "food"},
    {"english": "juice", "german": "Saft", "category": "food"},
    {"english": "tea", "german": "Tee", "category": "food"},
    {"english": "coffee", "german": "Kaffee", "category": "food"},
    {"english": "salt", "german": "Salz", "category": "food"},
    {"english": "sugar", "german": "Zucker", "category": "food"},
    {"english": "honey", "german": "Honig", "category": "food"},
    {"english": "jam", "german": "Marmelade", "category": "food"},
    {"english": "pizza", "german": "Pizza", "category": "food"},
    {"english": "sandwich", "german": "Sandwich", "category": "food"},

    # Colors (20 words)
    {"english": "red", "german": "rot", "category": "colors"},
    {"english": "blue", "german": "blau", "category": "colors"},
    {"english": "green", "german": "grün", "category": "colors"},
    {"english": "yellow", "german": "gelb", "category": "colors"},
    {"english": "orange", "german": "orange", "category": "colors"},
    {"english": "purple", "german": "lila", "category": "colors"},
    {"english": "pink", "german": "rosa", "category": "colors"},
    {"english": "brown", "german": "braun", "category": "colors"},
    {"english": "black", "german": "schwarz", "category": "colors"},
    {"english": "white", "german": "weiß", "category": "colors"},
    {"english": "gray", "german": "grau", "category": "colors"},
    {"english": "light", "german": "hell", "category": "colors"},
    {"english": "dark", "german": "dunkel", "category": "colors"},
    {"english": "bright", "german": "hell", "category": "colors"},
    {"english": "colorful", "german": "bunt", "category": "colors"},
    {"english": "gold", "german": "gold", "category": "colors"},
    {"english": "silver", "german": "silber", "category": "colors"},
    {"english": "bronze", "german": "bronze", "category": "colors"},
    {"english": "turquoise", "german": "türkis", "category": "colors"},
    {"english": "violet", "german": "violett", "category": "colors"},

    # Numbers (20 words)
    {"english": "zero", "german": "null", "category": "numbers"},
    {"english": "one", "german": "eins", "category": "numbers"},
    {"english": "two", "german": "zwei", "category": "numbers"},
    {"english": "three", "german": "drei", "category": "numbers"},
    {"english": "four", "german": "vier", "category": "numbers"},
    {"english": "five", "german": "fünf", "category": "numbers"},
    {"english": "six", "german": "sechs", "category": "numbers"},
    {"english": "seven", "german": "sieben", "category": "numbers"},
    {"english": "eight", "german": "acht", "category": "numbers"},
    {"english": "nine", "german": "neun", "category": "numbers"},
    {"english": "ten", "german": "zehn", "category": "numbers"},
    {"english": "eleven", "german": "elf", "category": "numbers"},
    {"english": "twelve", "german": "zwölf", "category": "numbers"},
    {"english": "thirteen", "german": "dreizehn", "category": "numbers"},
    {"english": "fourteen", "german": "vierzehn", "category": "numbers"},
    {"english": "fifteen", "german": "fünfzehn", "category": "numbers"},
    {"english": "twenty", "german": "zwanzig", "category": "numbers"},
    {"english": "thirty", "german": "dreißig", "category": "numbers"},
    {"english": "fifty", "german": "fünfzig", "category": "numbers"},
    {"english": "hundred", "german": "hundert", "category": "numbers"},

    # Body Parts (30 words)
    {"english": "head", "german": "Kopf", "category": "body"},
    {"english": "face", "german": "Gesicht", "category": "body"},
    {"english": "eye", "german": "Auge", "category": "body"},
    {"english": "nose", "german": "Nase", "category": "body"},
    {"english": "mouth", "german": "Mund", "category": "body"},
    {"english": "ear", "german": "Ohr", "category": "body"},
    {"english": "tooth", "german": "Zahn", "category": "body"},
    {"english": "tongue", "german": "Zunge", "category": "body"},
    {"english": "neck", "german": "Hals", "category": "body"},
    {"english": "shoulder", "german": "Schulter", "category": "body"},
    {"english": "arm", "german": "Arm", "category": "body"},
    {"english": "hand", "german": "Hand", "category": "body"},
    {"english": "finger", "german": "Finger", "category": "body"},
    {"english": "thumb", "german": "Daumen", "category": "body"},
    {"english": "chest", "german": "Brust", "category": "body"},
    {"english": "stomach", "german": "Bauch", "category": "body"},
    {"english": "back", "german": "Rücken", "category": "body"},
    {"english": "leg", "german": "Bein", "category": "body"},
    {"english": "knee", "german": "Knie", "category": "body"},
    {"english": "foot", "german": "Fuß", "category": "body"},
    {"english": "toe", "german": "Zehe", "category": "body"},
    {"english": "skin", "german": "Haut", "category": "body"},
    {"english": "hair", "german": "Haar", "category": "body"},
    {"english": "heart", "german": "Herz", "category": "body"},
    {"english": "brain", "german": "Gehirn", "category": "body"},
    {"english": "blood", "german": "Blut", "category": "body"},
    {"english": "bone", "german": "Knochen", "category": "body"},
    {"english": "muscle", "german": "Muskel", "category": "body"},
    {"english": "elbow", "german": "Ellbogen", "category": "body"},
    {"english": "wrist", "german": "Handgelenk", "category": "body"},

    # Household Items (30 words)
    {"english": "house", "german": "Haus", "category": "household"},
    {"english": "room", "german": "Zimmer", "category": "household"},
    {"english": "door", "german": "Tür", "category": "household"},
    {"english": "window", "german": "Fenster", "category": "household"},
    {"english": "wall", "german": "Wand", "category": "household"},
    {"english": "floor", "german": "Boden", "category": "household"},
    {"english": "ceiling", "german": "Decke", "category": "household"},
    {"english": "table", "german": "Tisch", "category": "household"},
    {"english": "chair", "german": "Stuhl", "category": "household"},
    {"english": "bed", "german": "Bett", "category": "household"},
    {"english": "sofa", "german": "Sofa", "category": "household"},
    {"english": "lamp", "german": "Lampe", "category": "household"},
    {"english": "television", "german": "Fernseher", "category": "household"},
    {"english": "computer", "german": "Computer", "category": "household"},
    {"english": "phone", "german": "Telefon", "category": "household"},
    {"english": "clock", "german": "Uhr", "category": "household"},
    {"english": "mirror", "german": "Spiegel", "category": "household"},
    {"english": "picture", "german": "Bild", "category": "household"},
    {"english": "book", "german": "Buch", "category": "household"},
    {"english": "pen", "german": "Stift", "category": "household"},
    {"english": "paper", "german": "Papier", "category": "household"},
    {"english": "bag", "german": "Tasche", "category": "household"},
    {"english": "key", "german": "Schlüssel", "category": "household"},
    {"english": "glass", "german": "Glas", "category": "household"},
    {"english": "plate", "german": "Teller", "category": "household"},
    {"english": "cup", "german": "Tasse", "category": "household"},
    {"english": "spoon", "german": "Löffel", "category": "household"},
    {"english": "fork", "german": "Gabel", "category": "household"},
    {"english": "knife", "german": "Messer", "category": "household"},
    {"english": "bottle", "german": "Flasche", "category": "household"}
]

# English Vocabulary - Intermediate Level (200 words)
ENGLISH_VOCABULARY_INTERMEDIATE = [
    # Advanced Animals (50 words)
    {"english": "kangaroo", "german": "Känguru", "category": "animals"},
    {"english": "koala", "german": "Koala", "category": "animals"},
    {"english": "rhinoceros", "german": "Nashorn", "category": "animals"},
    {"english": "hippopotamus", "german": "Nilpferd", "category": "animals"},
    {"english": "crocodile", "german": "Krokodil", "category": "animals"},
    {"english": "cheetah", "german": "Gepard", "category": "animals"},
    {"english": "leopard", "german": "Leopard", "category": "animals"},
    {"english": "jaguar", "german": "Jaguar", "category": "animals"},
    {"english": "panther", "german": "Panther", "category": "animals"},
    {"english": "wolf", "german": "Wolf", "category": "animals"},
    {"english": "fox", "german": "Fuchs", "category": "animals"},
    {"english": "deer", "german": "Reh", "category": "animals"},
    {"english": "moose", "german": "Elch", "category": "animals"},
    {"english": "reindeer", "german": "Rentier", "category": "animals"},
    {"english": "squirrel", "german": "Eichhörnchen", "category": "animals"},
    {"english": "hedgehog", "german": "Igel", "category": "animals"},
    {"english": "mole", "german": "Maulwurf", "category": "animals"},
    {"english": "bat", "german": "Fledermaus", "category": "animals"},
    {"english": "raccoon", "german": "Waschbär", "category": "animals"},
    {"english": "skunk", "german": "Stinktier", "category": "animals"},
    {"english": "porcupine", "german": "Stachelschwein", "category": "animals"},
    {"english": "beaver", "german": "Biber", "category": "animals"},
    {"english": "otter", "german": "Otter", "category": "animals"},
    {"english": "walrus", "german": "Walross", "category": "animals"},
    {"english": "octopus", "german": "Oktopus", "category": "animals"},
    {"english": "jellyfish", "german": "Qualle", "category": "animals"},
    {"english": "seahorse", "german": "Seepferdchen", "category": "animals"},
    {"english": "lobster", "german": "Hummer", "category": "animals"},
    {"english": "shrimp", "german": "Garnele", "category": "animals"},
    {"english": "oyster", "german": "Auster", "category": "animals"},
    {"english": "flamingo", "german": "Flamingo", "category": "animals"},
    {"english": "peacock", "german": "Pfau", "category": "animals"},
    {"english": "ostrich", "german": "Strauß", "category": "animals"},
    {"english": "pelican", "german": "Pelikan", "category": "animals"},
    {"english": "hummingbird", "german": "Kolibri", "category": "animals"},
    {"english": "woodpecker", "german": "Specht", "category": "animals"},
    {"english": "crow", "german": "Krähe", "category": "animals"},
    {"english": "raven", "german": "Rabe", "category": "animals"},
    {"english": "magpie", "german": "Elster", "category": "animals"},
    {"english": "stork", "german": "Storch", "category": "animals"},
    {"english": "crane", "german": "Kranich", "category": "animals"},
    {"english": "heron", "german": "Reiher", "category": "animals"},
    {"english": "seagull", "german": "Möwe", "category": "animals"},
    {"english": "albatross", "german": "Albatros", "category": "animals"},
    {"english": "vulture", "german": "Geier", "category": "animals"},
    {"english": "hawk", "german": "Habicht", "category": "animals"},
    {"english": "falcon", "german": "Falke", "category": "animals"},
    {"english": "kite", "german": "Milan", "category": "animals"},
    {"english": "buzzard", "german": "Bussard", "category": "animals"},
    {"english": "condor", "german": "Kondor", "category": "animals"},

    # Advanced Food (50 words)
    {"english": "pineapple", "german": "Ananas", "category": "food"},
    {"english": "mango", "german": "Mango", "category": "food"},
    {"english": "kiwi", "german": "Kiwi", "category": "food"},
    {"english": "papaya", "german": "Papaya", "category": "food"},
    {"english": "coconut", "german": "Kokosnuss", "category": "food"},
    {"english": "avocado", "german": "Avocado", "category": "food"},
    {"english": "fig", "german": "Feige", "category": "food"},
    {"english": "date", "german": "Dattel", "category": "food"},
    {"english": "raisin", "german": "Rosine", "category": "food"},
    {"english": "walnut", "german": "Walnuss", "category": "food"},
    {"english": "hazelnut", "german": "Haselnuss", "category": "food"},
    {"english": "almond", "german": "Mandel", "category": "food"},
    {"english": "peanut", "german": "Erdnuss", "category": "food"},
    {"english": "chestnut", "german": "Kastanie", "category": "food"},
    {"english": "cashew", "german": "Cashew", "category": "food"},
    {"english": "pistachio", "german": "Pistazie", "category": "food"},
    {"english": "macadamia", "german": "Macadamia", "category": "food"},
    {"english": "pecan", "german": "Pekannuss", "category": "food"},
    {"english": "pine nut", "german": "Pinienkern", "category": "food"},
    {"english": "sunflower seed", "german": "Sonnenblumenkern", "category": "food"},
    {"english": "pumpkin seed", "german": "Kürbiskern", "category": "food"},
    {"english": "sesame seed", "german": "Sesam", "category": "food"},
    {"english": "poppy seed", "german": "Mohn", "category": "food"},
    {"english": "chia seed", "german": "Chiasamen", "category": "food"},
    {"english": "flax seed", "german": "Leinsamen", "category": "food"},
    {"english": "quinoa", "german": "Quinoa", "category": "food"},
    {"english": "amaranth", "german": "Amarant", "category": "food"},
    {"english": "bulgur", "german": "Bulgur", "category": "food"},
    {"english": "couscous", "german": "Couscous", "category": "food"},
    {"english": "barley", "german": "Gerste", "category": "food"},
    {"english": "oats", "german": "Hafer", "category": "food"},
    {"english": "rye", "german": "Roggen", "category": "food"},
    {"english": "wheat", "german": "Weizen", "category": "food"},
    {"english": "spelt", "german": "Dinkel", "category": "food"},
    {"english": "buckwheat", "german": "Buchweizen", "category": "food"},
    {"english": "millet", "german": "Hirse", "category": "food"},
    {"english": "lentils", "german": "Linsen", "category": "food"},
    {"english": "chickpeas", "german": "Kichererbsen", "category": "food"},
    {"english": "kidney beans", "german": "Kidneybohnen", "category": "food"},
    {"english": "black beans", "german": "schwarze Bohnen", "category": "food"},
    {"english": "lima beans", "german": "Limabohnen", "category": "food"},
    {"english": "navy beans", "german": "weiße Bohnen", "category": "food"},
    {"english": "pinto beans", "german": "Pintobohnen", "category": "food"},
    {"english": "soy beans", "german": "Sojabohnen", "category": "food"},
    {"english": "tofu", "german": "Tofu", "category": "food"},
    {"english": "tempeh", "german": "Tempeh", "category": "food"},
    {"english": "seitan", "german": "Seitan", "category": "food"},
    {"english": "hummus", "german": "Hummus", "category": "food"},
    {"english": "tahini", "german": "Tahini", "category": "food"},
    {"english": "vinegar", "german": "Essig", "category": "food"},

    # Advanced Household/Technology (50 words)
    {"english": "refrigerator", "german": "Kühlschrank", "category": "household"},
    {"english": "microwave", "german": "Mikrowelle", "category": "household"},
    {"english": "dishwasher", "german": "Spülmaschine", "category": "household"},
    {"english": "washing machine", "german": "Waschmaschine", "category": "household"},
    {"english": "dryer", "german": "Trockner", "category": "household"},
    {"english": "vacuum cleaner", "german": "Staubsauger", "category": "household"},
    {"english": "iron", "german": "Bügeleisen", "category": "household"},
    {"english": "toaster", "german": "Toaster", "category": "household"},
    {"english": "blender", "german": "Mixer", "category": "household"},
    {"english": "coffee maker", "german": "Kaffeemaschine", "category": "household"},
    {"english": "kettle", "german": "Wasserkocher", "category": "household"},
    {"english": "oven", "german": "Ofen", "category": "household"},
    {"english": "stove", "german": "Herd", "category": "household"},
    {"english": "sink", "german": "Spüle", "category": "household"},
    {"english": "faucet", "german": "Wasserhahn", "category": "household"},
    {"english": "cabinet", "german": "Schrank", "category": "household"},
    {"english": "drawer", "german": "Schublade", "category": "household"},
    {"english": "shelf", "german": "Regal", "category": "household"},
    {"english": "closet", "german": "Kleiderschrank", "category": "household"},
    {"english": "wardrobe", "german": "Garderobe", "category": "household"},
    {"english": "curtain", "german": "Vorhang", "category": "household"},
    {"english": "blinds", "german": "Jalousie", "category": "household"},
    {"english": "carpet", "german": "Teppich", "category": "household"},
    {"english": "rug", "german": "Läufer", "category": "household"},
    {"english": "pillow", "german": "Kissen", "category": "household"},
    {"english": "blanket", "german": "Decke", "category": "household"},
    {"english": "sheet", "german": "Laken", "category": "household"},
    {"english": "towel", "german": "Handtuch", "category": "household"},
    {"english": "soap", "german": "Seife", "category": "household"},
    {"english": "shampoo", "german": "Shampoo", "category": "household"},
    {"english": "toothbrush", "german": "Zahnbürste", "category": "household"},
    {"english": "toothpaste", "german": "Zahnpasta", "category": "household"},
    {"english": "comb", "german": "Kamm", "category": "household"},
    {"english": "brush", "german": "Bürste", "category": "household"},
    {"english": "scissors", "german": "Schere", "category": "household"},
    {"english": "hammer", "german": "Hammer", "category": "household"},
    {"english": "screwdriver", "german": "Schraubenzieher", "category": "household"},
    {"english": "wrench", "german": "Schraubenschlüssel", "category": "household"},
    {"english": "drill", "german": "Bohrer", "category": "household"},
    {"english": "saw", "german": "Säge", "category": "household"},
    {"english": "nail", "german": "Nagel", "category": "household"},
    {"english": "screw", "german": "Schraube", "category": "household"},
    {"english": "bolt", "german": "Bolzen", "category": "household"},
    {"english": "nut", "german": "Mutter", "category": "household"},
    {"english": "washer", "german": "Unterlegscheibe", "category": "household"},
    {"english": "gasket", "german": "Dichtung", "category": "household"},
    {"english": "hinge", "german": "Scharnier", "category": "household"},
    {"english": "handle", "german": "Griff", "category": "household"},
    {"english": "knob", "german": "Knauf", "category": "household"},
    {"english": "switch", "german": "Schalter", "category": "household"},

    # Advanced Activities/Verbs (50 words)
    {"english": "create", "german": "erschaffen", "category": "activities"},
    {"english": "design", "german": "entwerfen", "category": "activities"},
    {"english": "develop", "german": "entwickeln", "category": "activities"},
    {"english": "innovate", "german": "innovieren", "category": "activities"},
    {"english": "discover", "german": "entdecken", "category": "activities"},
    {"english": "explore", "german": "erkunden", "category": "activities"},
    {"english": "investigate", "german": "untersuchen", "category": "activities"},
    {"english": "research", "german": "forschen", "category": "activities"},
    {"english": "analyze", "german": "analysieren", "category": "activities"},
    {"english": "examine", "german": "prüfen", "category": "activities"},
    {"english": "evaluate", "german": "bewerten", "category": "activities"},
    {"english": "assess", "german": "einschätzen", "category": "activities"},
    {"english": "measure", "german": "messen", "category": "activities"},
    {"english": "calculate", "german": "berechnen", "category": "activities"},
    {"english": "estimate", "german": "schätzen", "category": "activities"},
    {"english": "predict", "german": "vorhersagen", "category": "activities"},
    {"english": "forecast", "german": "prognostizieren", "category": "activities"},
    {"english": "anticipate", "german": "erwarten", "category": "activities"},
    {"english": "expect", "german": "erwarten", "category": "activities"},
    {"english": "assume", "german": "annehmen", "category": "activities"},
    {"english": "suppose", "german": "vermuten", "category": "activities"},
    {"english": "believe", "german": "glauben", "category": "activities"},
    {"english": "trust", "german": "vertrauen", "category": "activities"},
    {"english": "doubt", "german": "bezweifeln", "category": "activities"},
    {"english": "question", "german": "hinterfragen", "category": "activities"},
    {"english": "challenge", "german": "herausfordern", "category": "activities"},
    {"english": "compete", "german": "konkurrieren", "category": "activities"},
    {"english": "collaborate", "german": "zusammenarbeiten", "category": "activities"},
    {"english": "cooperate", "german": "kooperieren", "category": "activities"},
    {"english": "coordinate", "german": "koordinieren", "category": "activities"},
    {"english": "organize", "german": "organisieren", "category": "activities"},
    {"english": "manage", "german": "verwalten", "category": "activities"},
    {"english": "supervise", "german": "überwachen", "category": "activities"},
    {"english": "control", "german": "kontrollieren", "category": "activities"},
    {"english": "regulate", "german": "regulieren", "category": "activities"},
    {"english": "monitor", "german": "überwachen", "category": "activities"},
    {"english": "observe", "german": "beobachten", "category": "activities"},
    {"english": "watch", "german": "zusehen", "category": "activities"},
    {"english": "notice", "german": "bemerken", "category": "activities"},
    {"english": "recognize", "german": "erkennen", "category": "activities"},
    {"english": "identify", "german": "identifizieren", "category": "activities"},
    {"english": "distinguish", "german": "unterscheiden", "category": "activities"},
    {"english": "differentiate", "german": "differenzieren", "category": "activities"},
    {"english": "compare", "german": "vergleichen", "category": "activities"},
    {"english": "contrast", "german": "gegenüberstellen", "category": "activities"},
    {"english": "relate", "german": "in Beziehung setzen", "category": "activities"},
    {"english": "connect", "german": "verbinden", "category": "activities"},
    {"english": "link", "german": "verknüpfen", "category": "activities"},
    {"english": "associate", "german": "assoziieren", "category": "activities"},
    {"english": "combine", "german": "kombinieren", "category": "activities"}
]

# Simple Sentences for Translation (100 sentences)
ENGLISH_SENTENCES_BASIC = [
    # Family and Home (25 sentences)
    {"english": "I love my family.", "german": "Ich liebe meine Familie.", "category": "family"},
    {"english": "My mother cooks dinner.", "german": "Meine Mutter kocht das Abendessen.", "category": "family"},
    {"english": "My father reads the newspaper.", "german": "Mein Vater liest die Zeitung.", "category": "family"},
    {"english": "My brother plays football.", "german": "Mein Bruder spielt Fußball.", "category": "family"},
    {"english": "My sister likes music.", "german": "Meine Schwester mag Musik.", "category": "family"},
    {"english": "We live in a big house.", "german": "Wir wohnen in einem großen Haus.", "category": "family"},
    {"english": "Our dog is very friendly.", "german": "Unser Hund ist sehr freundlich.", "category": "family"},
    {"english": "The cat sleeps on the sofa.", "german": "Die Katze schläft auf dem Sofa.", "category": "family"},
    {"english": "Grandma tells stories.", "german": "Oma erzählt Geschichten.", "category": "family"},
    {"english": "Grandpa works in the garden.", "german": "Opa arbeitet im Garten.", "category": "family"},
    {"english": "The children play together.", "german": "Die Kinder spielen zusammen.", "category": "family"},
    {"english": "We eat breakfast together.", "german": "Wir frühstücken zusammen.", "category": "family"},
    {"english": "I help my parents.", "german": "Ich helfe meinen Eltern.", "category": "family"},
    {"english": "My room is very clean.", "german": "Mein Zimmer ist sehr sauber.", "category": "family"},
    {"english": "The kitchen smells good.", "german": "Die Küche riecht gut.", "category": "family"},
    {"english": "We watch TV in the evening.", "german": "Wir schauen abends fern.", "category": "family"},
    {"english": "I go to bed early.", "german": "Ich gehe früh ins Bett.", "category": "family"},
    {"english": "My alarm clock rings loudly.", "german": "Mein Wecker klingelt laut.", "category": "family"},
    {"english": "The telephone is ringing.", "german": "Das Telefon klingelt.", "category": "family"},
    {"english": "We have a beautiful garden.", "german": "Wir haben einen schönen Garten.", "category": "family"},
    {"english": "The flowers bloom in spring.", "german": "Die Blumen blühen im Frühling.", "category": "family"},
    {"english": "I water the plants.", "german": "Ich gieße die Pflanzen.", "category": "family"},
    {"english": "The sun shines through the window.", "german": "Die Sonne scheint durchs Fenster.", "category": "family"},
    {"english": "We open the windows.", "german": "Wir öffnen die Fenster.", "category": "family"},
    {"english": "The house is warm and cozy.", "german": "Das Haus ist warm und gemütlich.", "category": "family"},

    # School and Learning (25 sentences)
    {"english": "I go to school every day.", "german": "Ich gehe jeden Tag zur Schule.", "category": "school"},
    {"english": "My teacher is very nice.", "german": "Meine Lehrerin ist sehr nett.", "category": "school"},
    {"english": "We learn many subjects.", "german": "Wir lernen viele Fächer.", "category": "school"},
    {"english": "Mathematics is my favorite subject.", "german": "Mathematik ist mein Lieblingsfach.", "category": "school"},
    {"english": "I like reading books.", "german": "Ich lese gerne Bücher.", "category": "school"},
    {"english": "We write in our notebooks.", "german": "Wir schreiben in unsere Hefte.", "category": "school"},
    {"english": "The blackboard is clean.", "german": "Die Tafel ist sauber.", "category": "school"},
    {"english": "I raise my hand to answer.", "german": "Ich hebe die Hand zum Antworten.", "category": "school"},
    {"english": "The lesson begins at eight.", "german": "Der Unterricht beginnt um acht.", "category": "school"},
    {"english": "We have a break at ten.", "german": "Wir haben um zehn Pause.", "category": "school"},
    {"english": "I eat lunch at school.", "german": "Ich esse in der Schule zu Mittag.", "category": "school"},
    {"english": "My friends are in my class.", "german": "Meine Freunde sind in meiner Klasse.", "category": "school"},
    {"english": "We play together at recess.", "german": "Wir spielen zusammen in der Pause.", "category": "school"},
    {"english": "The library has many books.", "german": "Die Bibliothek hat viele Bücher.", "category": "school"},
    {"english": "I borrow books from the library.", "german": "Ich leihe Bücher aus der Bibliothek.", "category": "school"},
    {"english": "We do homework every day.", "german": "Wir machen jeden Tag Hausaufgaben.", "category": "school"},
    {"english": "I study for the test.", "german": "Ich lerne für die Prüfung.", "category": "school"},
    {"english": "The test is tomorrow.", "german": "Die Prüfung ist morgen.", "category": "school"},
    {"english": "I am prepared for the exam.", "german": "Ich bin für die Prüfung vorbereitet.", "category": "school"},
    {"english": "We get good grades.", "german": "Wir bekommen gute Noten.", "category": "school"},
    {"english": "The school year ends in summer.", "german": "Das Schuljahr endet im Sommer.", "category": "school"},
    {"english": "We have long holidays.", "german": "Wir haben lange Ferien.", "category": "school"},
    {"english": "I miss my classmates.", "german": "Ich vermisse meine Klassenkameraden.", "category": "school"},
    {"english": "School starts again in autumn.", "german": "Die Schule beginnt wieder im Herbst.", "category": "school"},
    {"english": "I look forward to learning.", "german": "Ich freue mich aufs Lernen.", "category": "school"},

    # Food and Meals (25 sentences)
    {"english": "I am hungry.", "german": "Ich habe Hunger.", "category": "food"},
    {"english": "I am thirsty.", "german": "Ich habe Durst.", "category": "food"},
    {"english": "The apple tastes sweet.", "german": "Der Apfel schmeckt süß.", "category": "food"},
    {"english": "I drink water every day.", "german": "Ich trinke jeden Tag Wasser.", "category": "food"},
    {"english": "Breakfast is the most important meal.", "german": "Das Frühstück ist die wichtigste Mahlzeit.", "category": "food"},
    {"english": "I eat bread with butter.", "german": "Ich esse Brot mit Butter.", "category": "food"},
    {"english": "My mother makes delicious soup.", "german": "Meine Mutter macht leckere Suppe.", "category": "food"},
    {"english": "We have lunch at twelve.", "german": "Wir essen um zwölf zu Mittag.", "category": "food"},
    {"english": "Dinner is ready at six.", "german": "Das Abendessen ist um sechs fertig.", "category": "food"},
    {"english": "I love chocolate cake.", "german": "Ich liebe Schokoladenkuchen.", "category": "food"},
    {"english": "Vegetables are healthy.", "german": "Gemüse ist gesund.", "category": "food"},
    {"english": "Fruits contain vitamins.", "german": "Obst enthält Vitamine.", "category": "food"},
    {"english": "I cook with my grandmother.", "german": "Ich koche mit meiner Großmutter.", "category": "food"},
    {"english": "The kitchen smells wonderful.", "german": "Die Küche riecht wunderbar.", "category": "food"},
    {"english": "We set the table together.", "german": "Wir decken zusammen den Tisch.", "category": "food"},
    {"english": "Please pass the salt.", "german": "Bitte reich mir das Salz.", "category": "food"},
    {"english": "The meal was delicious.", "german": "Das Essen war köstlich.", "category": "food"},
    {"english": "I wash the dishes.", "german": "Ich spüle das Geschirr.", "category": "food"},
    {"english": "We buy groceries at the market.", "german": "Wir kaufen Lebensmittel auf dem Markt.", "category": "food"},
    {"english": "Fresh bread smells good.", "german": "Frisches Brot riecht gut.", "category": "food"},
    {"english": "I prefer tea over coffee.", "german": "Ich bevorzuge Tee vor Kaffee.", "category": "food"},
    {"english": "Ice cream is cold and sweet.", "german": "Eis ist kalt und süß.", "category": "food"},
    {"english": "We bake cookies together.", "german": "Wir backen zusammen Kekse.", "category": "food"},
    {"english": "The restaurant serves good food.", "german": "Das Restaurant serviert gutes Essen.", "category": "food"},
    {"english": "I help in the kitchen.", "german": "Ich helfe in der Küche.", "category": "food"},

    # Weather and Seasons (25 sentences)
    {"english": "Today is a beautiful day.", "german": "Heute ist ein schöner Tag.", "category": "weather"},
    {"english": "The sun is shining brightly.", "german": "Die Sonne scheint hell.", "category": "weather"},
    {"english": "It is raining outside.", "german": "Es regnet draußen.", "category": "weather"},
    {"english": "The sky is cloudy.", "german": "Der Himmel ist bewölkt.", "category": "weather"},
    {"english": "Snow is falling from the sky.", "german": "Schnee fällt vom Himmel.", "category": "weather"},
    {"english": "The wind is blowing strongly.", "german": "Der Wind weht stark.", "category": "weather"},
    {"english": "There is a thunderstorm coming.", "german": "Ein Gewitter kommt.", "category": "weather"},
    {"english": "I see lightning in the distance.", "german": "Ich sehe Blitze in der Ferne.", "category": "weather"},
    {"english": "Thunder sounds very loud.", "german": "Donner klingt sehr laut.", "category": "weather"},
    {"english": "The temperature is rising.", "german": "Die Temperatur steigt.", "category": "weather"},
    {"english": "It is very hot today.", "german": "Es ist heute sehr heiß.", "category": "weather"},
    {"english": "Winter is cold and long.", "german": "Der Winter ist kalt und lang.", "category": "weather"},
    {"english": "Spring brings new life.", "german": "Der Frühling bringt neues Leben.", "category": "weather"},
    {"english": "Summer is my favorite season.", "german": "Der Sommer ist meine Lieblingsjahreszeit.", "category": "weather"},
    {"english": "Autumn leaves are colorful.", "german": "Herbstblätter sind bunt.", "category": "weather"},
    {"english": "I wear a coat in winter.", "german": "Ich trage einen Mantel im Winter.", "category": "weather"},
    {"english": "Flowers bloom in spring.", "german": "Blumen blühen im Frühling.", "category": "weather"},
    {"english": "We swim in summer.", "german": "Wir schwimmen im Sommer.", "category": "weather"},
    {"english": "Leaves fall in autumn.", "german": "Blätter fallen im Herbst.", "category": "weather"},
    {"english": "I need an umbrella.", "german": "Ich brauche einen Regenschirm.", "category": "weather"},
    {"english": "The rainbow appears after rain.", "german": "Der Regenbogen erscheint nach dem Regen.", "category": "weather"},
    {"english": "Fog makes visibility poor.", "german": "Nebel macht die Sicht schlecht.", "category": "weather"},
    {"english": "Frost covers the ground.", "german": "Frost bedeckt den Boden.", "category": "weather"},
    {"english": "The weather forecast is important.", "german": "Die Wettervorhersage ist wichtig.", "category": "weather"},
    {"english": "I check the weather daily.", "german": "Ich prüfe täglich das Wetter.", "category": "weather"}
]

# Advanced Sentences for Translation (100 sentences)
ENGLISH_SENTENCES_INTERMEDIATE = [
    # Technology and Modern Life (25 sentences)
    {"english": "Technology changes our daily lives.", "german": "Technologie verändert unser tägliches Leben.", "category": "technology"},
    {"english": "Computers help us work more efficiently.", "german": "Computer helfen uns, effizienter zu arbeiten.", "category": "technology"},
    {"english": "The internet connects people worldwide.", "german": "Das Internet verbindet Menschen weltweit.", "category": "technology"},
    {"english": "Social media influences communication.", "german": "Soziale Medien beeinflussen die Kommunikation.", "category": "technology"},
    {"english": "Smartphones have many useful features.", "german": "Smartphones haben viele nützliche Funktionen.", "category": "technology"},
    {"english": "Apps make life more convenient.", "german": "Apps machen das Leben bequemer.", "category": "technology"},
    {"english": "Artificial intelligence is developing rapidly.", "german": "Künstliche Intelligenz entwickelt sich schnell.", "category": "technology"},
    {"english": "Robots perform various tasks automatically.", "german": "Roboter führen verschiedene Aufgaben automatisch aus.", "category": "technology"},
    {"english": "Digital transformation affects all industries.", "german": "Digitale Transformation betrifft alle Branchen.", "category": "technology"},
    {"english": "Cloud computing enables remote work.", "german": "Cloud Computing ermöglicht Remote-Arbeit.", "category": "technology"},
    {"english": "Cybersecurity becomes increasingly important.", "german": "Cybersicherheit wird immer wichtiger.", "category": "technology"},
    {"english": "Data protection is a fundamental right.", "german": "Datenschutz ist ein Grundrecht.", "category": "technology"},
    {"english": "Virtual reality creates immersive experiences.", "german": "Virtual Reality schafft immersive Erlebnisse.", "category": "technology"},
    {"english": "3D printing revolutionizes manufacturing.", "german": "3D-Druck revolutioniert die Herstellung.", "category": "technology"},
    {"english": "Electric vehicles reduce emissions.", "german": "Elektrofahrzeuge reduzieren Emissionen.", "category": "technology"},
    {"english": "Renewable energy sources are sustainable.", "german": "Erneuerbare Energiequellen sind nachhaltig.", "category": "technology"},
    {"english": "Smart homes increase energy efficiency.", "german": "Smart Homes erhöhen die Energieeffizienz.", "category": "technology"},
    {"english": "Biotechnology advances medical treatments.", "german": "Biotechnologie verbessert medizinische Behandlungen.", "category": "technology"},
    {"english": "Nanotechnology opens new possibilities.", "german": "Nanotechnologie eröffnet neue Möglichkeiten.", "category": "technology"},
    {"english": "Quantum computing promises breakthrough performance.", "german": "Quantencomputing verspricht bahnbrechende Leistung.", "category": "technology"},
    {"english": "Machine learning improves decision making.", "german": "Maschinelles Lernen verbessert Entscheidungsfindung.", "category": "technology"},
    {"english": "Blockchain technology ensures transparency.", "german": "Blockchain-Technologie gewährleistet Transparenz.", "category": "technology"},
    {"english": "Internet of Things connects everyday objects.", "german": "Internet der Dinge vernetzt Alltagsgegenstände.", "category": "technology"},
    {"english": "5G networks enable faster communication.", "german": "5G-Netzwerke ermöglichen schnellere Kommunikation.", "category": "technology"},
    {"english": "Automation changes the job market.", "german": "Automatisierung verändert den Arbeitsmarkt.", "category": "technology"},

    # Environment and Sustainability (25 sentences)
    {"english": "Climate change affects the entire planet.", "german": "Klimawandel betrifft den gesamten Planeten.", "category": "environment"},
    {"english": "We must protect our environment.", "german": "Wir müssen unsere Umwelt schützen.", "category": "environment"},
    {"english": "Pollution threatens wildlife and ecosystems.", "german": "Verschmutzung bedroht Wildtiere und Ökosysteme.", "category": "environment"},
    {"english": "Recycling reduces waste significantly.", "german": "Recycling reduziert Abfall erheblich.", "category": "environment"},
    {"english": "Sustainable development is essential.", "german": "Nachhaltige Entwicklung ist unerlässlich.", "category": "environment"},
    {"english": "Deforestation destroys natural habitats.", "german": "Entwaldung zerstört natürliche Lebensräume.", "category": "environment"},
    {"english": "Ocean pollution affects marine life.", "german": "Meeresverschmutzung betrifft das Meereleben.", "category": "environment"},
    {"english": "Greenhouse gases cause global warming.", "german": "Treibhausgase verursachen globale Erwärmung.", "category": "environment"},
    {"english": "Alternative energy sources are crucial.", "german": "Alternative Energiequellen sind entscheidend.", "category": "environment"},
    {"english": "Solar panels generate clean electricity.", "german": "Solarpanels erzeugen sauberen Strom.", "category": "environment"},
    {"english": "Wind turbines harness natural power.", "german": "Windturbinen nutzen natürliche Kraft.", "category": "environment"},
    {"english": "Hydroelectric dams produce renewable energy.", "german": "Wasserkraftwerke produzieren erneuerbare Energie.", "category": "environment"},
    {"english": "Geothermal energy comes from Earth's heat.", "german": "Geothermische Energie stammt aus der Erdwärme.", "category": "environment"},
    {"english": "Biodiversity supports ecosystem stability.", "german": "Biodiversität unterstützt Ökosystemstabilität.", "category": "environment"},
    {"english": "Conservation efforts protect endangered species.", "german": "Naturschutzmaßnahmen schützen bedrohte Arten.", "category": "environment"},
    {"english": "National parks preserve natural landscapes.", "german": "Nationalparks bewahren natürliche Landschaften.", "category": "environment"},
    {"english": "Urban planning affects environmental quality.", "german": "Stadtplanung beeinflusst Umweltqualität.", "category": "environment"},
    {"english": "Green buildings reduce environmental impact.", "german": "Grüne Gebäude reduzieren Umweltauswirkungen.", "category": "environment"},
    {"english": "Public transportation decreases carbon emissions.", "german": "Öffentlicher Verkehr verringert CO2-Emissionen.", "category": "environment"},
    {"english": "Organic farming avoids harmful pesticides.", "german": "Biologische Landwirtschaft vermeidet schädliche Pestizide.", "category": "environment"},
    {"english": "Water conservation becomes increasingly important.", "german": "Wasserschutz wird immer wichtiger.", "category": "environment"},
    {"english": "Air quality monitoring protects public health.", "german": "Luftqualitätsüberwachung schützt die öffentliche Gesundheit.", "category": "environment"},
    {"english": "Eco-friendly products reduce environmental damage.", "german": "Umweltfreundliche Produkte reduzieren Umweltschäden.", "category": "environment"},
    {"english": "Environmental education raises awareness.", "german": "Umweltbildung schärft das Bewusstsein.", "category": "environment"},
    {"english": "Individual actions contribute to global solutions.", "german": "Individuelle Handlungen tragen zu globalen Lösungen bei.", "category": "environment"},

    # Health and Medicine (25 sentences)
    {"english": "Regular exercise maintains physical fitness.", "german": "Regelmäßige Bewegung erhält körperliche Fitness.", "category": "health"},
    {"english": "Balanced nutrition supports overall health.", "german": "Ausgewogene Ernährung unterstützt die Gesamtgesundheit.", "category": "health"},
    {"english": "Preventive care reduces disease risk.", "german": "Vorsorge reduziert Krankheitsrisiken.", "category": "health"},
    {"english": "Mental health is equally important.", "german": "Geistige Gesundheit ist gleich wichtig.", "category": "health"},
    {"english": "Stress management improves quality of life.", "german": "Stressmanagement verbessert die Lebensqualität.", "category": "health"},
    {"english": "Medical research advances treatment options.", "german": "Medizinische Forschung verbessert Behandlungsmöglichkeiten.", "category": "health"},
    {"english": "Vaccines prevent serious diseases.", "german": "Impfungen verhindern schwere Krankheiten.", "category": "health"},
    {"english": "Early diagnosis improves treatment outcomes.", "german": "Frühe Diagnose verbessert Behandlungsergebnisse.", "category": "health"},
    {"english": "Telemedicine increases healthcare access.", "german": "Telemedizin erhöht den Zugang zur Gesundheitsversorgung.", "category": "health"},
    {"english": "Personalized medicine tailors treatments.", "german": "Personalisierte Medizin passt Behandlungen an.", "category": "health"},
    {"english": "Pharmaceutical companies develop new drugs.", "german": "Pharmaunternehmen entwickeln neue Medikamente.", "category": "health"},
    {"english": "Clinical trials test medication safety.", "german": "Klinische Studien testen Medikamentensicherheit.", "category": "health"},
    {"english": "Healthcare systems face many challenges.", "german": "Gesundheitssysteme stehen vor vielen Herausforderungen.", "category": "health"},
    {"english": "Medical technology improves diagnostic accuracy.", "german": "Medizintechnik verbessert diagnostische Genauigkeit.", "category": "health"},
    {"english": "Rehabilitation helps patients recover.", "german": "Rehabilitation hilft Patienten bei der Genesung.", "category": "health"},
    {"english": "Health insurance provides financial protection.", "german": "Krankenversicherung bietet finanziellen Schutz.", "category": "health"},
    {"english": "Public health policies affect entire populations.", "german": "Öffentliche Gesundheitspolitik betrifft ganze Bevölkerungen.", "category": "health"},
    {"english": "Epidemic preparedness is crucial.", "german": "Epidemievorbereitung ist entscheidend.", "category": "health"},
    {"english": "Health education promotes wellness.", "german": "Gesundheitsbildung fördert Wohlbefinden.", "category": "health"},
    {"english": "Alternative medicine offers complementary treatments.", "german": "Alternativmedizin bietet ergänzende Behandlungen.", "category": "health"},
    {"english": "Genetic testing reveals predispositions.", "german": "Gentests zeigen Veranlagungen auf.", "category": "health"},
    {"english": "Organ transplantation saves lives.", "german": "Organtransplantation rettet Leben.", "category": "health"},
    {"english": "Medical ethics guides healthcare decisions.", "german": "Medizinethik leitet Gesundheitsentscheidungen.", "category": "health"},
    {"english": "Healthcare workers deserve recognition.", "german": "Gesundheitspersonal verdient Anerkennung.", "category": "health"},
    {"english": "Global health cooperation prevents pandemics.", "german": "Globale Gesundheitskooperation verhindert Pandemien.", "category": "health"},

    # Education and Society (25 sentences)
    {"english": "Education shapes future generations.", "german": "Bildung prägt zukünftige Generationen.", "category": "education"},
    {"english": "Lifelong learning becomes increasingly important.", "german": "Lebenslanges Lernen wird immer wichtiger.", "category": "education"},
    {"english": "Digital literacy is essential nowadays.", "german": "Digitale Kompetenz ist heutzutage unerlässlich.", "category": "education"},
    {"english": "Online learning expands educational access.", "german": "Online-Lernen erweitert Bildungszugang.", "category": "education"},
    {"english": "Teachers play a crucial role.", "german": "Lehrer spielen eine entscheidende Rolle.", "category": "education"},
    {"english": "Educational inequality affects social mobility.", "german": "Bildungsungleichheit beeinflusst soziale Mobilität.", "category": "education"},
    {"english": "Multicultural education promotes understanding.", "german": "Multikulturelle Bildung fördert Verständnis.", "category": "education"},
    {"english": "Critical thinking skills are valuable.", "german": "Kritische Denkfähigkeiten sind wertvoll.", "category": "education"},
    {"english": "Creativity and innovation drive progress.", "german": "Kreativität und Innovation treiben Fortschritt voran.", "category": "education"},
    {"english": "Collaboration skills enhance teamwork.", "german": "Kooperationsfähigkeiten verbessern Teamarbeit.", "category": "education"},
    {"english": "Research universities advance knowledge.", "german": "Forschungsuniversitäten erweitern Wissen.", "category": "education"},
    {"english": "Vocational training provides practical skills.", "german": "Berufsausbildung vermittelt praktische Fähigkeiten.", "category": "education"},
    {"english": "Student exchange programs broaden perspectives.", "german": "Studentenaustauschprogramme erweitern Perspektiven.", "category": "education"},
    {"english": "Educational funding affects quality.", "german": "Bildungsfinanzierung beeinflusst Qualität.", "category": "education"},
    {"english": "School infrastructure needs improvement.", "german": "Schulinfrastruktur braucht Verbesserung.", "category": "education"},
    {"english": "Standardized testing measures achievement.", "german": "Standardisierte Tests messen Leistung.", "category": "education"},
    {"english": "Inclusive education serves all students.", "german": "Inklusive Bildung dient allen Schülern.", "category": "education"},
    {"english": "Educational technology transforms classrooms.", "german": "Bildungstechnologie transformiert Klassenzimmer.", "category": "education"},
    {"english": "Parent involvement supports student success.", "german": "Elternbeteiligung unterstützt Schülererfolg.", "category": "education"},
    {"english": "Community partnerships enhance learning.", "german": "Gemeinschaftspartnerschaften verbessern das Lernen.", "category": "education"},
    {"english": "Educational policy shapes systems.", "german": "Bildungspolitik formt Systeme.", "category": "education"},
    {"english": "International cooperation advances education.", "german": "Internationale Zusammenarbeit fördert Bildung.", "category": "education"},
    {"english": "Educational research informs best practices.", "german": "Bildungsforschung informiert über bewährte Praktiken.", "category": "education"},
    {"english": "Democratic values support education.", "german": "Demokratische Werte unterstützen Bildung.", "category": "education"},
    {"english": "Social responsibility guides educational goals.", "german": "Gesellschaftliche Verantwortung leitet Bildungsziele.", "category": "education"}
]