# Complete German Content Expansion for Weekly Star Tracker
# Target: 500 spelling words, 120 word types, 150 fill-blanks per grade

# Grade 2 Spelling Words - Complete Extension (500 words)
GRADE2_SPELLING_COMPLETE = [
    # Animals (100 words)
    {"correct": "Hund", "wrong": ["Hunt", "Hundt", "Huhnd"]},
    {"correct": "Katze", "wrong": ["Kaze", "Katse", "Kazte"]},
    {"correct": "Maus", "wrong": ["Mauss", "Mous", "Mauß"]},
    {"correct": "Vogel", "wrong": ["Fogel", "Vohgel", "Vogol"]},
    {"correct": "Fisch", "wrong": ["Fish", "Fischh", "Visch"]},
    {"correct": "Pferd", "wrong": ["Pfehrd", "Pferdt", "Bferd"]},
    {"correct": "Kuh", "wrong": ["Kue", "Kuuh", "Guh"]},
    {"correct": "Schwein", "wrong": ["Schwain", "Schwien", "Schwein"]},
    {"correct": "Schaf", "wrong": ["Schaaf", "Schahf", "Schaf"]},
    {"correct": "Ziege", "wrong": ["Siege", "Zieke", "Ziehe"]},
    {"correct": "Hase", "wrong": ["Haase", "Hahse", "Gase"]},
    {"correct": "Kaninchen", "wrong": ["Kanienchen", "Kaninchhen", "Ganinchen"]},
    {"correct": "Hamster", "wrong": ["Hamsder", "Hampster", "Gamster"]},
    {"correct": "Meerschweinchen", "wrong": ["Mehrschweinchen", "Meerschwienchen", "Meeerschweinchen"]},
    {"correct": "Frosch", "wrong": ["Vrogsch", "Froschh", "Froshc"]},
    {"correct": "Kröte", "wrong": ["Gröte", "Kröhte", "Krötte"]},
    {"correct": "Schnecke", "wrong": ["Schnegke", "Schncke", "Schneckke"]},
    {"correct": "Käfer", "wrong": ["Gäfer", "Käfher", "Käffer"]},
    {"correct": "Biene", "wrong": ["Biehne", "Bienee", "Piene"]},
    {"correct": "Fliege", "wrong": ["Vliege", "Flieke", "Fliehe"]},
    {"correct": "Spinne", "wrong": ["Sbinne", "Spinnee", "Zbinne"]},
    {"correct": "Ameise", "wrong": ["Ahmeise", "Ameihse", "Amaise"]},
    {"correct": "Wurm", "wrong": ["Wuhrm", "Wurmm", "Vurm"]},
    {"correct": "Marienkäfer", "wrong": ["Mariehnkäfer", "Mariengäfer", "Maarienkäfer"]},
    {"correct": "Schmetterling", "wrong": ["Schmetehrling", "Schmetterlink", "Schmetterlingg"]},
    {"correct": "Libelle", "wrong": ["Libbelle", "Libehle", "Lipelle"]},
    {"correct": "Wespe", "wrong": ["Wesbpe", "Wehspe", "Wezspe"]},
    {"correct": "Hummel", "wrong": ["Hummell", "Gummel", "Hummmel"]},
    {"correct": "Grille", "wrong": ["Krille", "Grile", "Grielle"]},
    {"correct": "Heuschrecke", "wrong": ["Heuschregke", "Heuschreckke", "Geuschrecke"]},
    {"correct": "Elefant", "wrong": ["Elefandt", "Elehfant", "Elephannt"]},
    {"correct": "Löwe", "wrong": ["Löhwe", "Löwee", "Loewe"]},
    {"correct": "Tiger", "wrong": ["Diger", "Tigher", "Tieger"]},
    {"correct": "Bär", "wrong": ["Bähr", "Bärr", "Paer"]},
    {"correct": "Affe", "wrong": ["Ahffe", "Affee", "Apfe"]},
    {"correct": "Giraffe", "wrong": ["Kirafe", "Giraffe", "Girrafe"]},
    {"correct": "Zebra", "wrong": ["Sebra", "Zebraa", "Cebra"]},
    {"correct": "Nilpferd", "wrong": ["Nilbferd", "Nillpferd", "Nihlpferd"]},
    {"correct": "Krokodil", "wrong": ["Grocodil", "Krokodill", "Kroggodil"]},
    {"correct": "Schlange", "wrong": ["Schlangge", "Schlahge", "Schlanke"]},
    {"correct": "Schildkröte", "wrong": ["Schildkröhte", "Schildgröte", "Schiltkröte"]},
    {"correct": "Pinguin", "wrong": ["Binguin", "Pinguhin", "Pinkuin"]},
    {"correct": "Eisbär", "wrong": ["Eispär", "Eisbähr", "Aizbär"]},
    {"correct": "Seehund", "wrong": ["Sehund", "Seegundt", "Zeehund"]},
    {"correct": "Delfin", "wrong": ["Delphin", "Dellfin", "Telfin"]},
    {"correct": "Wal", "wrong": ["Wahl", "Wall", "Val"]},
    {"correct": "Hai", "wrong": ["Haai", "Haj", "Gay"]},
    {"correct": "Seestern", "wrong": ["Sehstern", "Seesterrn", "Zeestern"]},
    {"correct": "Krabbe", "wrong": ["Grabbee", "Krabbee", "Grappe"]},
    {"correct": "Muschel", "wrong": ["Muschell", "Muschel", "Muschel"]},
    {"correct": "Qualle", "wrong": ["Kwalle", "Quallee", "Quahlle"]},
    {"correct": "Oktopus", "wrong": ["Ogktopus", "Oktohpus", "Oktobus"]},
    {"correct": "Storch", "wrong": ["Shtorch", "Storchh", "Storkh"]},
    {"correct": "Schwan", "wrong": ["Schwahn", "Schwann", "Schvan"]},
    {"correct": "Ente", "wrong": ["Ehnte", "Entee", "Endte"]},
    {"correct": "Gans", "wrong": ["Kahns", "Ganss", "Gaans"]},
    {"correct": "Huhn", "wrong": ["Guhn", "Huhnn", "Huuhn"]},
    {"correct": "Hahn", "wrong": ["Gahn", "Hahnn", "Haahn"]},
    {"correct": "Küken", "wrong": ["Gühken", "Kükenn", "Kühkenn"]},
    {"correct": "Papagei", "wrong": ["Bahpagei", "Papagaj", "Papakai"]},
    {"correct": "Wellensittich", "wrong": ["Welensittich", "Wellensitich", "Wellenzittich"]},
    {"correct": "Kanarienvogel", "wrong": ["Ganarienvogel", "Kanarienfogel", "Kanariehnvogel"]},
    {"correct": "Adler", "wrong": ["Ahdler", "Adlerr", "Atler"]},
    {"correct": "Falke", "wrong": ["Valke", "Falkee", "Fahlke"]},
    {"correct": "Eule", "wrong": ["Aule", "Eulee", "Ehule"]},
    {"correct": "Specht", "wrong": ["Zbecht", "Speht", "Specht"]},
    {"correct": "Amsel", "wrong": ["Ahmsel", "Amsell", "Amzel"]},
    {"correct": "Drossel", "wrong": ["Drosell", "Drossell", "Trossel"]},
    {"correct": "Rotkehlchen", "wrong": ["Rohtkehlchen", "Rotkehlchenn", "Rohtgehllchen"]},
    {"correct": "Spatz", "wrong": ["Zbatz", "Spatzz", "Spahtz"]},
    {"correct": "Meise", "wrong": ["Mahise", "Meisee", "Meihse"]},
    {"correct": "Fink", "wrong": ["Vink", "Finkk", "Fihnk"]},
    {"correct": "Schwalbe", "wrong": ["Schwalhbe", "Schwalpe", "Schwaalbe"]},
    {"correct": "Kranich", "wrong": ["Grahnich", "Kranichh", "Krahnich"]},
    {"correct": "Reiher", "wrong": ["Raher", "Reiherr", "Raiher"]},
    {"correct": "Möwe", "wrong": ["Mööwe", "Möhwe", "Moewe"]},
    {"correct": "Pelikan", "wrong": ["Belikan", "Pelikahn", "Pelikkan"]},
    {"correct": "Flamingo", "wrong": ["Vlamingo", "Flamingho", "Flaminkho"]},
    {"correct": "Strauß", "wrong": ["Shtrauß", "Strauhs", "Strauhß"]},
    {"correct": "Emu", "wrong": ["Ahmu", "Emuu", "Emuh"]},
    {"correct": "Pfau", "wrong": ["Bfau", "Pfauh", "Pfaau"]},
    {"correct": "Taube", "wrong": ["Daube", "Taubee", "Tauhbe"]},
    {"correct": "Krähe", "wrong": ["Grähe", "Krähee", "Kraehe"]},
    {"correct": "Rabe", "wrong": ["Rahbe", "Rabee", "Raabe"]},
    {"correct": "Elster", "wrong": ["Alster", "Elsder", "Elzter"]},
    {"correct": "Star", "wrong": ["Shtar", "Starr", "Staar"]},
    {"correct": "Nachtigall", "wrong": ["Nachdigall", "Nachtigahll", "Nahchtigall"]},
    {"correct": "Lerche", "wrong": ["Lehrche", "Lerchee", "Laerche"]},
    {"correct": "Kiebitz", "wrong": ["Giebitz", "Kiebitzz", "Kiehbitz"]},
    {"correct": "Bussard", "wrong": ["Pusard", "Bussahrdt", "Buzard"]},
    {"correct": "Habicht", "wrong": ["Gabicht", "Habichht", "Habiccht"]},
    {"correct": "Sperber", "wrong": ["Zberber", "Sperberr", "Spaerber"]},
    {"correct": "Milan", "wrong": ["Milahn", "Milann", "Mielahn"]},
    {"correct": "Geier", "wrong": ["Kaier", "Geierr", "Gaier"]},
    {"correct": "Albatros", "wrong": ["Ahlbatros", "Albadros", "Albahros"]},
    {"correct": "Pelztier", "wrong": ["Beltier", "Pelztiehr", "Pelzdier"]},
    {"correct": "Reh", "wrong": ["Raeh", "Rehh", "Reeh"]},
    {"correct": "Hirsch", "wrong": ["Girsch", "Hirschh", "Hihrsch"]},
    {"correct": "Wildschwein", "wrong": ["Vildschwein", "Wildschwainn", "Vildschvein"]},
    {"correct": "Fuchs", "wrong": ["Vuchss", "Fuchss", "Fuhs"]},
    {"correct": "Wolf", "wrong": ["Volf", "Wolff", "Vollf"]},
    {"correct": "Dachs", "wrong": ["Dahchss", "Dachss", "Taghs"]},
    {"correct": "Marder", "wrong": ["Mahrder", "Mardehr", "Martehr"]},
    {"correct": "Otter", "wrong": ["Ohter", "Otterr", "Other"]},
    {"correct": "Biber", "wrong": ["Piper", "Biberr", "Bieber"]},
    {"correct": "Eichhörnchen", "wrong": ["Aichhörnchen", "Eichhörncghen", "Eichhörnchenn"]},
    {"correct": "Igel", "wrong": ["Ihgel", "Igell", "Ykel"]},
    {"correct": "Maulwurf", "wrong": ["Mahlwurf", "Maulwuhrf", "Mauhlfurf"]},
    {"correct": "Fledermaus", "wrong": ["Vledermaus", "Fledehrmauss", "Fledermauhss"]},
    
    # Food Items (100 words)
    {"correct": "Apfel", "wrong": ["Appfel", "Apfol", "Aphel"]},
    {"correct": "Birne", "wrong": ["Birrne", "Bierne", "Pierne"]},
    {"correct": "Banane", "wrong": ["Bannane", "Banahne", "Banaene"]},
    {"correct": "Orange", "wrong": ["Oranje", "Orangge", "Oranghe"]},
    {"correct": "Zitrone", "wrong": ["Sitrone", "Zitrohne", "Zidrohne"]},
    {"correct": "Traube", "wrong": ["Drahube", "Trauhbe", "Traupe"]},
    {"correct": "Erdbeere", "wrong": ["Erdbehre", "Erdbeeere", "Erdpeere"]},
    {"correct": "Himbeere", "wrong": ["Himpbeere", "Himbeehre", "Gimbere"]},
    {"correct": "Blaubeere", "wrong": ["Blauhbeere", "Blaupeere", "Plaubeere"]},
    {"correct": "Kirsche", "wrong": ["Girsche", "Kirschhe", "Kirrsche"]},
    {"correct": "Pflaume", "wrong": ["Bflaume", "Pflauhme", "Pflauhm"]},
    {"correct": "Pfirsich", "wrong": ["Bfirsich", "Pfirschh", "Pvirsich"]},
    {"correct": "Aprikose", "wrong": ["Ahprikose", "Aprigose", "Aprikohse"]},
    {"correct": "Nektarine", "wrong": ["Negktarine", "Nektarihne", "Negktariene"]},
    {"correct": "Melone", "wrong": ["Mehone", "Mellone", "Melohne"]},
    {"correct": "Wassermelone", "wrong": ["Wasermelone", "Wassermelohne", "Vasermelone"]},
    {"correct": "Ananas", "wrong": ["Ahnaas", "Ananass", "Ananahs"]},
    {"correct": "Mango", "wrong": ["Manggo", "Mahngo", "Manko"]},
    {"correct": "Kiwi", "wrong": ["Giwi", "Kiwii", "Kivy"]},
    {"correct": "Papaya", "wrong": ["Bahpaya", "Papahya", "Babaya"]},
    {"correct": "Kokosnuss", "wrong": ["Gokosnuss", "Kokosnuhss", "Kokoznuss"]},
    {"correct": "Avocado", "wrong": ["Ahvocado", "Avogado", "Afocado"]},
    {"correct": "Feige", "wrong": ["Vaige", "Feigee", "Faige"]},
    {"correct": "Dattel", "wrong": ["Dahtell", "Dattell", "Tatel"]},
    {"correct": "Rosine", "wrong": ["Rohsine", "Rosihnne", "Rozine"]},
    {"correct": "Nuss", "wrong": ["Nuß", "Nusss", "Nuhs"]},
    {"correct": "Walnuss", "wrong": ["Wahlnuss", "Walnuß", "Valnuss"]},
    {"correct": "Haselnuss", "wrong": ["Gaselnuss", "Haselnuß", "Hazelnuss"]},
    {"correct": "Mandel", "wrong": ["Mahdel", "Mandell", "Mantell"]},
    {"correct": "Erdnuss", "wrong": ["Aerdnuss", "Erdnuß", "Ehrdnuss"]},
    {"correct": "Kastanie", "wrong": ["Gastanie", "Kastanhie", "Kashtanie"]},
    {"correct": "Eichel", "wrong": ["Aichel", "Eichell", "Eihchel"]},
    {"correct": "Brot", "wrong": ["Broht", "Brott", "Proht"]},
    {"correct": "Weißbrot", "wrong": ["Vaißbrot", "Weißbroht", "Weihßbrot"]},
    {"correct": "Schwarzbrot", "wrong": ["Schwartzbrot", "Schwarzbroht", "Zchwartzbrot"]},
    {"correct": "Vollkornbrot", "wrong": ["Folkornbrot", "Vollgornbrot", "Vollkornbroht"]},
    {"correct": "Brötchen", "wrong": ["Pröhchen", "Brötchenn", "Brötgen"]},
    {"correct": "Semmel", "wrong": ["Zemmel", "Semmell", "Semell"]},
    {"correct": "Baguette", "wrong": ["Pakette", "Baguete", "Baguhette"]},
    {"correct": "Toast", "wrong": ["Doast", "Toasht", "Toasd"]},
    {"correct": "Zwieback", "wrong": ["Swiepack", "Zwiebagk", "Zwiepagk"]},
    {"correct": "Keks", "wrong": ["Gekss", "Kekss", "Kehks"]},
    {"correct": "Kekse", "wrong": ["Gekse", "Keksee", "Kehkse"]},
    {"correct": "Plätzchen", "wrong": ["Blätzchen", "Plätzchenn", "Plähtzchen"]},
    {"correct": "Lebkuchen", "wrong": ["Lebguchen", "Lebkuhchen", "Lepkuchen"]},
    {"correct": "Stollen", "wrong": ["Shtollen", "Stollenn", "Stolenn"]},
    {"correct": "Kuchen", "wrong": ["Guhchen", "Kuchenn", "Kuuchenn"]},
    {"correct": "Torte", "wrong": ["Dohrte", "Tortee", "Tohrte"]},
    {"correct": "Muffin", "wrong": ["Mufinn", "Mufffin", "Muffhin"]},
    {"correct": "Donut", "wrong": ["Dohnut", "Donuht", "Tonuht"]},
    {"correct": "Croissant", "wrong": ["Groissant", "Croissahnt", "Croisant"]},
    {"correct": "Pudding", "wrong": ["Buding", "Pudingg", "Putingg"]},
    {"correct": "Joghurt", "wrong": ["Yoghurt", "Joghuhrt", "Yokurt"]},
    {"correct": "Quark", "wrong": ["Quargg", "Quhark", "Quarkk"]},
    {"correct": "Sahne", "wrong": ["Zaahne", "Sahnee", "Sahne"]},
    {"correct": "Schlagsahne", "wrong": ["Schlagsaahne", "Schlagzahne", "Schlagsahhnee"]},
    {"correct": "Butter", "wrong": ["Buter", "Butterr", "Putter"]},
    {"correct": "Margarine", "wrong": ["Magharine", "Margarihne", "Markaarine"]},
    {"correct": "Käse", "wrong": ["Kääse", "Kaese", "Kässe"]},
    {"correct": "Gouda", "wrong": ["Kouda", "Goudaa", "Gohda"]},
    {"correct": "Emmentaler", "wrong": ["Ementaler", "Emmenhtaler", "Emmentahlerr"]},
    {"correct": "Camembert", "wrong": ["Gämembert", "Camempert", "Camempbert"]},
    {"correct": "Brie", "wrong": ["Prrie", "Briee", "Brie"]},
    {"correct": "Mozzarella", "wrong": ["Motzarella", "Mozzarellla", "Mozarrella"]},
    {"correct": "Parmesan", "wrong": ["Bahrmesan", "Parmesahn", "Parmezan"]},
    {"correct": "Feta", "wrong": ["Veta", "Fettaa", "Fetha"]},
    {"correct": "Ricotta", "wrong": ["Rigotta", "Ricotha", "Ricohta"]},
    {"correct": "Frischkäse", "wrong": ["Vrischkäse", "Frischgäse", "Frischkääse"]},
    {"correct": "Schmelzkäse", "wrong": ["Schmeltzkäse", "Schmelsgäse", "Schmelzkääse"]},
    {"correct": "Hartkäse", "wrong": ["Garhkäse", "Hartgäse", "Hartkääse"]},
    {"correct": "Weichkäse", "wrong": ["Vaichkäse", "Weichgäse", "Weichkääse"]},
    {"correct": "Ziegenkäse", "wrong": ["Siegenkäse", "Ziegengäse", "Ziegenkääse"]},
    {"correct": "Schafskäse", "wrong": ["Schavskäse", "Schafsgäse", "Schafskääse"]},
    {"correct": "Milch", "wrong": ["Millch", "Mihlch", "Milkh"]},
    {"correct": "Vollmilch", "wrong": ["Follmilch", "Vollmihlch", "Vollmilch"]},
    {"correct": "Magermilch", "wrong": ["Maghermilch", "Magermillch", "Makermilch"]},
    {"correct": "Kondensmilch", "wrong": ["Gondensmilch", "Kondensmihlch", "Kondhensmilch"]},
    {"correct": "Buttermilch", "wrong": ["Puhtermilch", "Buttermillch", "Buttehrmihlch"]},
    {"correct": "Kakao", "wrong": ["Gakao", "Kakaoh", "Kakaoo"]},
    {"correct": "Schokolade", "wrong": ["Schogolade", "Schokolahde", "Zchodgolade"]},
    {"correct": "Bonbon", "wrong": ["Ponpon", "Bonbohn", "Bohnbohn"]},
    {"correct": "Gummibärchen", "wrong": ["Kummibärchen", "Gummipärchen", "Gummibäärchen"]},
    {"correct": "Lutscher", "wrong": ["Luhtscher", "Lutscherr", "Luxcher"]},
    {"correct": "Zuckerstange", "wrong": ["Sugkerstange", "Zuckerstanhge", "Zuckehrstange"]},
    {"correct": "Marshmallow", "wrong": ["Marshmahlow", "Marshmallohw", "Marshmalow"]},
    {"correct": "Nougat", "wrong": ["Nohgat", "Nougaht", "Nougatt"]},
    {"correct": "Marzipan", "wrong": ["Mahrzipan", "Marsipan", "Marzibahn"]},
    {"correct": "Leberwurst", "wrong": ["Lebervurst", "Leberwuhst", "Leperwurst"]},
    {"correct": "Bratwurst", "wrong": ["Pratwurst", "Bratwuhst", "Bradhwurst"]},
    {"correct": "Weißwurst", "wrong": ["Vaißwurst", "Weißwuhst", "Weihßwurst"]},
    {"correct": "Blutwurst", "wrong": ["Pluhtewurst", "Blutwuhst", "Bluhtwurst"]},
    {"correct": "Mettwurst", "wrong": ["Mehtwurst", "Metwuhst", "Methwurst"]},
    {"correct": "Salami", "wrong": ["Zalami", "Salamii", "Salahmi"]},
    {"correct": "Schinken", "wrong": ["Schinkenn", "Schinhken", "Zchinkenn"]},
    {"correct": "Speck", "wrong": ["Zbeck", "Specck", "Spegk"]},
    {"correct": "Würstchen", "wrong": ["Vürstchen", "Würstchenn", "Würsthcenn"]},
    {"correct": "Fleischbällchen", "wrong": ["Vlaischbällchen", "Fleischpällchen", "Fleischbäällchenn"]},
    {"correct": "Karotte", "wrong": ["Gahrote", "Karotee", "Karrote"]},
    {"correct": "Möhre", "wrong": ["Möhree", "Möhrre", "Moehre"]},
    {"correct": "Kartoffel", "wrong": ["Gartoffel", "Kartoffell", "Kartohffel"]},
    {"correct": "Zwiebel", "wrong": ["Swiebel", "Zwiebell", "Zwiehbel"]},
    {"correct": "Knoblauch", "wrong": ["Gnohblauch", "Knoblauhch", "Gnohblauhch"]},
    {"correct": "Tomate", "wrong": ["Domahte", "Tomatee", "Tomaate"]},
    {"correct": "Gurke", "wrong": ["Kuhke", "Gurkee", "Guhrke"]},
    {"correct": "Paprika", "wrong": ["Bahprika", "Paprikaa", "Pahprika"]},
    {"correct": "Salat", "wrong": ["Zahlat", "Salaht", "Salaat"]},
    {"correct": "Kohl", "wrong": ["Gohl", "Kohll", "Kool"]},
    {"correct": "Blumenkohl", "wrong": ["Plumenkohl", "Blumengohl", "Blumenkohll"]},
    {"correct": "Brokkoli", "wrong": ["Prokkoli", "Brokkolii", "Broggoli"]},
    {"correct": "Spinat", "wrong": ["Zbinat", "Spinaht", "Spinatt"]},
    {"correct": "Erbsen", "wrong": ["Ehrbsen", "Erbsenn", "Ehrbsenn"]},
    {"correct": "Bohnen", "wrong": ["Pohnenn", "Bohnenn", "Boehnenn"]},
    
    # Household Items (100 words)
    {"correct": "Tisch", "wrong": ["Dishch", "Tischh", "Tiisch"]},
    {"correct": "Stuhl", "wrong": ["Shtuhl", "Stuhll", "Ztuhl"]},
    {"correct": "Bank", "wrong": ["Pahnk", "Bankk", "Bangk"]},
    {"correct": "Bett", "wrong": ["Pet", "Bettt", "Beht"]},
    {"correct": "Schrank", "wrong": ["Schrankk", "Schrangk", "Srank"]},
    {"correct": "Regal", "wrong": ["Rekahl", "Regall", "Rehgal"]},
    {"correct": "Lampe", "wrong": ["Lahmpee", "Lammpe", "Lahmpe"]},
    {"correct": "Spiegel", "wrong": ["Zbiehgel", "Spiegell", "Spieegel"]},
    {"correct": "Fernseher", "wrong": ["Vernsehehr", "Fernzehher", "Fernseegher"]},
    {"correct": "Radio", "wrong": ["Rahdio", "Radioo", "Rahdioh"]},
    {"correct": "Telefon", "wrong": ["Delefon", "Telefohn", "Telephon"]},
    {"correct": "Computer", "wrong": ["Gomputer", "Computher", "Komputer"]},
    {"correct": "Laptop", "wrong": ["Lahptop", "Laptohp", "Labhtop"]},
    {"correct": "Tablet", "wrong": ["Daplet", "Tableet", "Tabhlet"]},
    {"correct": "Handy", "wrong": ["Gahndy", "Handyy", "Gantdy"]},
    {"correct": "Kamera", "wrong": ["Gamera", "Kameraa", "Kamehra"]},
    {"correct": "Uhr", "wrong": ["Uhhr", "Uhrr", "Ohr"]},
    {"correct": "Wecker", "wrong": ["Vegker", "Weckehr", "Wekker"]},
    {"correct": "Kalender", "wrong": ["Galender", "Kalentder", "Kahlender"]},
    {"correct": "Buch", "wrong": ["Puch", "Buchh", "Buhch"]},
    {"correct": "Zeitschrift", "wrong": ["Saitschrift", "Zeitschrifft", "Zeitshrift"]},
    {"correct": "Zeitung", "wrong": ["Saitung", "Zeitungg", "Zaitung"]},
    {"correct": "Heft", "wrong": ["Gehft", "Hefft", "Hehft"]},
    {"correct": "Stift", "wrong": ["Shtift", "Stifft", "Stifht"]},
    {"correct": "Kugelschreiber", "wrong": ["Gugelschreiber", "Kugelscgreiber", "Kugelschraiberr"]},
    {"correct": "Bleistift", "wrong": ["Plaeistift", "Bleisthift", "Bleistifft"]},
    {"correct": "Radiergummi", "wrong": ["Rahdiergummi", "Radiergummii", "Radiehrgummi"]},
    {"correct": "Lineal", "wrong": ["Lihneal", "Lineahl", "Linehaal"]},
    {"correct": "Schere", "wrong": ["Schehre", "Scheere", "Scgeere"]},
    {"correct": "Kleber", "wrong": ["Gleber", "Kleberr", "Klehber"]},
    {"correct": "Papier", "wrong": ["Bahpier", "Papiehr", "Papyher"]},
    {"correct": "Briefumschlag", "wrong": ["Priefumschlag", "Briefumschlagg", "Briefuhmschlag"]},
    {"correct": "Brief", "wrong": ["Prief", "Brieff", "Bryeff"]},
    {"correct": "Postkarte", "wrong": ["Bostkarte", "Postgarte", "Postkahte"]},
    {"correct": "Paket", "wrong": ["Bahket", "Pakeet", "Pagett"]},
    {"correct": "Tasche", "wrong": ["Dasche", "Taschee", "Tahsche"]},
    {"correct": "Rucksack", "wrong": ["Ruckzack", "Rucksagk", "Rugksagk"]},
    {"correct": "Koffer", "wrong": ["Goffer", "Kofferr", "Kohaer"]},
    {"correct": "Regenschirm", "wrong": ["Rehgenschirm", "Regenschihrm", "Regehnschirm"]},
    {"correct": "Schlüssel", "wrong": ["Schlühssel", "Schlüssell", "Schluessel"]},
    {"correct": "Portemonnaie", "wrong": ["Bortemonnaie", "Portemonnahie", "Portemonnaihe"]},
    {"correct": "Geldbeutel", "wrong": ["Keldbeutel", "Geldbeutell", "Geldbeuhtell"]},
    {"correct": "Münze", "wrong": ["Mühnze", "Münzee", "Muenze"]},
    {"correct": "Geld", "wrong": ["Kehld", "Geldd", "Keltd"]},
    {"correct": "Schein", "wrong": ["Scgain", "Scheihn", "Schainn"]},
    {"correct": "Karte", "wrong": ["Garte", "Kartee", "Kahrte"]},
    {"correct": "Brille", "wrong": ["Prille", "Brillee", "Brile"]},
    {"correct": "Sonnenbrille", "wrong": ["Zonnenbrille", "Sonnenbrillee", "Sonnehnbrille"]},
    {"correct": "Schmuck", "wrong": ["Schmugk", "Schmuckk", "Schmugg"]},
    {"correct": "Ring", "wrong": ["Rihngg", "Ringg", "Ryngg"]},
    {"correct": "Kette", "wrong": ["Gette", "Kettee", "Kehtte"]},
    {"correct": "Armband", "wrong": ["Ahrmband", "Armbandd", "Ahrmbandt"]},
    {"correct": "Ohrringe", "wrong": ["Ohrrihnge", "Ohrringee", "Ohrrinhge"]},
    {"correct": "Kerze", "wrong": ["Gehrtse", "Kersee", "Kerhze"]},
    {"correct": "Seife", "wrong": ["Zaife", "Seifee", "Saife"]},
    {"correct": "Handtuch", "wrong": ["Gandtuch", "Handtuchh", "Handtuhch"]},
    {"correct": "Zahnbürste", "wrong": ["Sahnbürste", "Zahnbürshtee", "Zaanbürste"]},
    {"correct": "Zahnpasta", "wrong": ["Sahnpasta", "Zahnpahsta", "Zaanpasta"]},
    {"correct": "Shampoo", "wrong": ["Shampoh", "Shampooo", "Zhamphoo"]},
    {"correct": "Duschgel", "wrong": ["Duschkel", "Duschgell", "Tushgel"]},
    {"correct": "Creme", "wrong": ["Greme", "Cremee", "Crehme"]},
    {"correct": "Parfüm", "wrong": ["Barhfüm", "Parfühm", "Parfuemm"]},
    {"correct": "Deo", "wrong": ["Deoh", "Deoo", "Tehoo"]},
    {"correct": "Medikament", "wrong": ["Mehikament", "Medikamehnt", "Medikamentt"]},
    {"correct": "Pflaster", "wrong": ["Bflaster", "Pflahster", "Pflaschter"]},
    {"correct": "Verband", "wrong": ["Fehbandt", "Verbandd", "Vehrband"]},
    {"correct": "Thermometer", "wrong": ["Dhermometer", "Thermomether", "Thermometr"]},
    {"correct": "Waage", "wrong": ["Waahge", "Waagee", "Vaage"]},
    {"correct": "Spiegel", "wrong": ["Zbiehgel", "Spiegell", "Spieegel"]},
    {"correct": "Kamm", "wrong": ["Gahm", "Kammm", "Kahm"]},
    {"correct": "Bürste", "wrong": ["Pürste", "Bürshtee", "Buerstee"]},
    {"correct": "Haargummi", "wrong": ["Gaargummi", "Haargummii", "Haahrgummi"]},
    {"correct": "Haarspray", "wrong": ["Gaarspray", "Haarsprray", "Hahspray"]},
    {"correct": "Föhn", "wrong": ["Vöhn", "Föhnn", "Foehn"]},
    {"correct": "Handschuhe", "wrong": ["Gandschuhe", "Handschuhee", "Handscguhe"]},
    {"correct": "Mütze", "wrong": ["Mühze", "Mützee", "Muetze"]},
    {"correct": "Hut", "wrong": ["Guht", "Hutt", "Gutt"]},
    {"correct": "Kappe", "wrong": ["Gappe", "Kappee", "Kahppe"]},
    {"correct": "Schal", "wrong": ["Schahl", "Schalll", "Zchal"]},
    {"correct": "Gürtel", "wrong": ["Kürtel", "Gürtell", "Guertel"]},
    {"correct": "Hosenträger", "wrong": ["Gosenträger", "Hosenträhger", "Hosentrahger"]},
    {"correct": "Socken", "wrong": ["Zoggen", "Sockenn", "Sogken"]},
    {"correct": "Strümpfe", "wrong": ["Shtrümpfe", "Strümpfee", "Strühmfe"]},
    {"correct": "Unterwäsche", "wrong": ["Uhnerwäsche", "Unterwasche", "Untehrwaesche"]},
    {"correct": "Schlafanzug", "wrong": ["Schlahfanzug", "Schlafaanzuhg", "Schlafahnsuhg"]},
    {"correct": "Pyjama", "wrong": ["Byjama", "Pyjahmaa", "Pyyamah"]},
    {"correct": "Bademantel", "wrong": ["Pahdemantel", "Bademahtel", "Bademanntell"]},
    {"correct": "Hausschuhe", "wrong": ["Gaußschuhe", "Hausschue", "Hausscguhe"]},
    {"correct": "Pantoffeln", "wrong": ["Pahntoffeln", "Pantofeln", "Bantoffeln"]},
    {"correct": "Stiefel", "wrong": ["Shtifel", "Stieell", "Ztiefel"]},
    {"correct": "Sandalen", "wrong": ["Zahdalen", "Sandalenn", "Santalen"]},
    {"correct": "Turnschuhe", "wrong": ["Durnschuhe", "Turnschue", "Turnschuehe"]},
    {"correct": "Sneaker", "wrong": ["Znehker", "Sneakerr", "Snehaker"]},
    {"correct": "Hausschuhe", "wrong": ["Gaußschuhe", "Hausschue", "Hausscguhe"]},
    {"correct": "Ballerinas", "wrong": ["Palerinas", "Ballerinass", "Ballerinahs"]},
    {"correct": "Pumps", "wrong": ["Bumpss", "Pumps", "Pumbss"]},
    {"correct": "Absatz", "wrong": ["Ahbsatz", "Absatss", "Ahbzatz"]},
    
    # Colors, Shapes, Nature (100 words)
    {"correct": "rot", "wrong": ["roht", "rott", "rodt"]},
    {"correct": "blau", "wrong": ["plauh", "blauuh", "blauu"]},
    {"correct": "grün", "wrong": ["krün", "grünn", "kruenn"]},
    {"correct": "gelb", "wrong": ["kelb", "gellb", "gehlp"]},
    {"correct": "schwarz", "wrong": ["schwarts", "schwarts", "schvarts"]},
    {"correct": "weiß", "wrong": ["vaiß", "weihß", "weis"]},
    {"correct": "grau", "wrong": ["krauh", "grauu", "graau"]},
    {"correct": "braun", "wrong": ["praun", "braunn", "bronn"]},
    {"correct": "rosa", "wrong": ["rohsa", "rosaa", "rozaa"]},
    {"correct": "lila", "wrong": ["lihlah", "lillaa", "lielaa"]},
    {"correct": "violett", "wrong": ["fiorett", "violehtt", "violett"]},
    {"correct": "orange", "wrong": ["orahge", "orangee", "oranhge"]},
    {"correct": "türkis", "wrong": ["dürkis", "türkiss", "tuerkiss"]},
    {"correct": "beige", "wrong": ["paige", "beigee", "baihe"]},
    {"correct": "gold", "wrong": ["kohld", "goldd", "kolt"]},
    {"correct": "silber", "wrong": ["zilber", "silberr", "silbher"]},
    {"correct": "bronze", "wrong": ["pronze", "bronsee", "bronce"]},
    {"correct": "hell", "wrong": ["gell", "helll", "hehl"]},
    {"correct": "dunkel", "wrong": ["tunkel", "dunkell", "dungkel"]},
    {"correct": "bunt", "wrong": ["punt", "buntt", "buhnt"]},
    {"correct": "Kreis", "wrong": ["Grais", "Kreiss", "Kraiss"]},
    {"correct": "Quadrat", "wrong": ["Gvadrat", "Quadraht", "Quadratt"]},
    {"correct": "Rechteck", "wrong": ["Rehchteck", "Rechtegk", "Rechteckk"]},
    {"correct": "Dreieck", "wrong": ["Treiegk", "Dreieckk", "Draieck"]},
    {"correct": "Oval", "wrong": ["Ohval", "Ovaal", "Ovahl"]},
    {"correct": "Stern", "wrong": ["Shtern", "Sterrn", "Ztern"]},
    {"correct": "Herz", "wrong": ["Gehrs", "Herrz", "Herts"]},
    {"correct": "Mond", "wrong": ["Mohnd", "Mondd", "Mont"]},
    {"correct": "Sonne", "wrong": ["Sohne", "Sonnee", "Zonhe"]},
    {"correct": "Himmel", "wrong": ["Gimmel", "Himmell", "Himml"]},
    {"correct": "Wolke", "wrong": ["Wohlke", "Wolkee", "Volke"]},
    {"correct": "Regen", "wrong": ["Rehgen", "Regenn", "Reeken"]},
    {"correct": "Schnee", "wrong": ["Schnehe", "Schneee", "Schne"]},
    {"correct": "Wind", "wrong": ["Wihnd", "Windd", "Vind"]},
    {"correct": "Sturm", "wrong": ["Shturm", "Stuhrm", "Zturm"]},
    {"correct": "Gewitter", "wrong": ["Kehwitter", "Gewitterr", "Gewihter"]},
    {"correct": "Blitz", "wrong": ["Plitz", "Blitss", "Blihs"]},
    {"correct": "Donner", "wrong": ["Dohner", "Donneer", "Toner"]},
    {"correct": "Regenbogen", "wrong": ["Rehgenbogen", "Regenpogen", "Regehnbogen"]},
    {"correct": "Nebel", "wrong": ["Nehbel", "Nebell", "Nehpel"]},
    {"correct": "Eis", "wrong": ["Aiß", "Eiss", "Ays"]},
    {"correct": "Frost", "wrong": ["Vrost", "Frostt", "Frohst"]},
    {"correct": "Hitze", "wrong": ["Gitse", "Hitzee", "Hihtze"]},
    {"correct": "Kälte", "wrong": ["Gälte", "Kältee", "Kaelte"]},
    {"correct": "Wärme", "wrong": ["Wärme", "Wärmee", "Waermme"]},
    {"correct": "Baum", "wrong": ["Pauhm", "Baumm", "Boum"]},
    {"correct": "Blatt", "wrong": ["Plaht", "Blaht", "Blat"]},
    {"correct": "Ast", "wrong": ["Asht", "Astt", "Ahst"]},
    {"correct": "Wurzel", "wrong": ["Wuhrzel", "Wurzell", "Vurzel"]},
    {"correct": "Stamm", "wrong": ["Shhtamm", "Stammm", "Stam"]},
    {"correct": "Blume", "wrong": ["Pluhme", "Blumee", "Bluhm"]},
    {"correct": "Gras", "wrong": ["Krahs", "Grahs", "Graas"]},
    {"correct": "Wiese", "wrong": ["Wiehse", "Wiesee", "Vyese"]},
    {"correct": "Feld", "wrong": ["Velt", "Feldd", "Fehldt"]},
    {"correct": "Wald", "wrong": ["Wahlt", "Waldd", "Vald"]},
    {"correct": "Berg", "wrong": ["Pehrg", "Bergg", "Behrk"]},
    {"correct": "Tal", "wrong": ["Dahl", "Tall", "Taal"]},
    {"correct": "Hügel", "wrong": ["Gühgel", "Hügell", "Hueggel"]},
    {"correct": "Fluss", "wrong": ["Vluss", "Fluhss", "Flus"]},
    {"correct": "Bach", "wrong": ["Pahch", "Bachh", "Bacgh"]},
    {"correct": "See", "wrong": ["Zehe", "Seee", "Se"]},
    {"correct": "Teich", "wrong": ["Daich", "Teichh", "Taych"]},
    {"correct": "Meer", "wrong": ["Mehhr", "Meerr", "Mear"]},
    {"correct": "Ozean", "wrong": ["Osean", "Ozaean", "Ozeahn"]},
    {"correct": "Strand", "wrong": ["Shtrahnd", "Strandd", "Strant"]},
    {"correct": "Sand", "wrong": ["Zahnd", "Sandd", "Sandt"]},
    {"correct": "Stein", "wrong": ["Shtain", "Steinn", "Staine"]},
    {"correct": "Fels", "wrong": ["Vels", "Felss", "Fehlz"]},
    {"correct": "Höhle", "wrong": ["Göhle", "Höhllee", "Hoele"]},
    {"correct": "Insel", "wrong": ["Ihnsel", "Insell", "Ynsell"]},
    {"correct": "Halbinsel", "wrong": ["Galbinsel", "Halbihsel", "Halbinsell"]},
    {"correct": "Bucht", "wrong": ["Puhcht", "Buchht", "Buggt"]},
    {"correct": "Klippe", "wrong": ["Glippe", "Klippee", "Klihhpe"]},
    {"correct": "Düne", "wrong": ["Tühne", "Dünee", "Duehne"]},
    {"correct": "Moor", "wrong": ["Mohhr", "Moorr", "Mooor"]},
    {"correct": "Sumpf", "wrong": ["Zumbf", "Sumpff", "Zumpff"]},
    {"correct": "Wüste", "wrong": ["Wühste", "Wüstee", "Wueste"]},
    {"correct": "Oase", "wrong": ["Oahse", "Oasee", "Oaaze"]},
    {"correct": "Dschungel", "wrong": ["Tschungel", "Dschungell", "Dschunghel"]},
    {"correct": "Regenwald", "wrong": ["Rehgenwald", "Regenwaldd", "Regehnwald"]},
    {"correct": "Steppe", "wrong": ["Shteppe", "Steppee", "Stehpe"]},
    {"correct": "Savanne", "wrong": ["Zavanne", "Savannee", "Safanne"]},
    {"correct": "Tundra", "wrong": ["Dundra", "Tundraa", "Tundhra"]},
    {"correct": "Gletscher", "wrong": ["Kletscher", "Gletscherr", "Gletsher"]},
    {"correct": "Eisberg", "wrong": ["Aisberg", "Eisbergg", "Aisperg"]},
    {"correct": "Pol", "wrong": ["Bohl", "Poll", "Pooll"]},
    {"correct": "Nordpol", "wrong": ["Nortpol", "Nordpoll", "Nohrdpol"]},
    {"correct": "Südpol", "wrong": ["Zühpol", "Südpoll", "Suedpoll"]},
    {"correct": "Äquator", "wrong": ["Äkator", "Äquaktor", "Aequatoor"]},
    {"correct": "Kontinent", "wrong": ["Gontinenent", "Kontinenht", "Kontinentt"]},
    {"correct": "Land", "wrong": ["Lahndt", "Landd", "Landt"]},
    {"correct": "Erde", "wrong": ["Ehrdee", "Erdee", "Erte"]},
    {"correct": "Planet", "wrong": ["Blanet", "Planeet", "Planeht"]},
    {"correct": "Weltall", "wrong": ["Veltall", "Weltahll", "Vehltall"]},
    {"correct": "Universum", "wrong": ["Uhniversum", "Univehrsum", "Uniehrum"]},
    {"correct": "Galaxie", "wrong": ["Kahlaxie", "Galaxiee", "Galaksihe"]},
    {"correct": "Sonnensystem", "wrong": ["Zonnensystem", "Sonnensyshtem", "Sonnehnzystem"]},
    {"correct": "Rakete", "wrong": ["Rahgete", "Raketee", "Ragete"]},
    {"correct": "Raumschiff", "wrong": ["Rauhmschiff", "Raumschifff", "Raumzchiff"]},
    {"correct": "Astronaut", "wrong": ["Ahstronaut", "Astronahut", "Astrohhaut"]},
    {"correct": "Satellit", "wrong": ["Zatehlit", "Satelliht", "Satelittt"]},
    {"correct": "Raumstation", "wrong": ["Rauhstation", "Raumstahtion", "Rauhmshtahtion"]}
]

# Grade 2 Word Type Examples - Complete (120 examples)
GRADE2_WORD_TYPES_COMPLETE = [
    # Nomen (Nouns) - 40 examples
    {"sentence": "Der Hund bellt laut.", "word": "Hund", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die Katze schläft.", "word": "Katze", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Ein Apfel ist rot.", "word": "Apfel", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Das Auto fährt.", "word": "Auto", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die Blume blüht.", "word": "Blume", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Der Ball ist rund.", "word": "Ball", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Das Haus ist groß.", "word": "Haus", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Der Baum wächst.", "word": "Baum", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die Sonne scheint.", "word": "Sonne", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Das Kind spielt.", "word": "Kind", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Der Tisch steht dort.", "word": "Tisch", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die Mutter kocht.", "word": "Mutter", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Der Vater arbeitet.", "word": "Vater", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Das Buch liegt da.", "word": "Buch", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die Schule beginnt.", "word": "Schule", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Der Stuhl ist alt.", "word": "Stuhl", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Das Wasser fließt.", "word": "Wasser", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die Milch ist weiß.", "word": "Milch", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Der Fisch schwimmt.", "word": "Fisch", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Das Brot schmeckt gut.", "word": "Brot", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die Lampe leuchtet.", "word": "Lampe", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Der Himmel ist blau.", "word": "Himmel", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Das Fenster ist offen.", "word": "Fenster", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die Tür geht auf.", "word": "Tür", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Der Garten ist schön.", "word": "Garten", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Das Pferd läuft schnell.", "word": "Pferd", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die Uhr zeigt drei.", "word": "Uhr", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Der Käse ist lecker.", "word": "Käse", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Das Ei ist rund.", "word": "Ei", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die Butter ist gelb.", "word": "Butter", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Der Zucker ist süß.", "word": "Zucker", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Das Salz ist weiß.", "word": "Salz", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die Suppe ist heiß.", "word": "Suppe", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Der Kuchen schmeckt.", "word": "Kuchen", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Das Spielzeug ist neu.", "word": "Spielzeug", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die Puppe ist hübsch.", "word": "Puppe", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Der Teddy ist weich.", "word": "Teddy", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Das Puzzle ist schwer.", "word": "Puzzle", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die Farbe ist schön.", "word": "Farbe", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Der Pinsel malt.", "word": "Pinsel", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},

    # Verben (Verbs) - 40 examples
    {"sentence": "Der Hund bellt laut.", "word": "bellt", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die Katze schläft tief.", "word": "schläft", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Das Auto fährt schnell.", "word": "fährt", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die Blume blüht schön.", "word": "blüht", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Der Baum wächst hoch.", "word": "wächst", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die Sonne scheint hell.", "word": "scheint", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Das Kind spielt gern.", "word": "spielt", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die Mutter kocht gut.", "word": "kocht", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Der Vater arbeitet viel.", "word": "arbeitet", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Das Wasser fließt klar.", "word": "fließt", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Der Fisch schwimmt schnell.", "word": "schwimmt", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die Lampe leuchtet hell.", "word": "leuchtet", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die Tür öffnet sich.", "word": "öffnet", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Das Pferd läuft schnell.", "word": "läuft", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die Uhr tickt laut.", "word": "tickt", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Der Wind weht stark.", "word": "weht", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Es regnet stark.", "word": "regnet", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die Vögel singen schön.", "word": "singen", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Wir lachen viel.", "word": "lachen", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Sie weinen traurig.", "word": "weinen", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Ich lese gern.", "word": "lese", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Du schreibst schön.", "word": "schreibst", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Er rechnet gut.", "word": "rechnet", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Sie malt bunt.", "word": "malt", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Wir basteln gern.", "word": "basteln", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Sie tanzen schön.", "word": "tanzen", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Ich springe hoch.", "word": "springe", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Du rennst schnell.", "word": "rennst", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Er klettert hoch.", "word": "klettert", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Sie hüpft fröhlich.", "word": "hüpft", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Das Baby schläft tief.", "word": "schläft", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Der Hahn kräht laut.", "word": "kräht", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die Kuh muht tief.", "word": "muht", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Das Schwein grunzt.", "word": "grunzt", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Der Frosch quakt.", "word": "quakt", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die Ente schwimmt.", "word": "schwimmt", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Der Vogel fliegt hoch.", "word": "fliegt", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die Biene summt.", "word": "summt", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Der Käfer krabbelt.", "word": "krabbelt", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die Schnecke kriecht.", "word": "kriecht", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},

    # Adjektive (Adjectives) - 40 examples
    {"sentence": "Der große Hund bellt.", "word": "große", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die schöne Blume blüht.", "word": "schöne", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Das schnelle Auto fährt.", "word": "schnelle", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Ein runder Ball rollt.", "word": "runder", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Das alte Haus steht.", "word": "alte", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Der hohe Baum wächst.", "word": "hohe", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die helle Sonne scheint.", "word": "helle", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Das kleine Kind spielt.", "word": "kleine", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Der neue Tisch steht.", "word": "neue", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die warme Milch schmeckt.", "word": "warme", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Das kalte Wasser fließt.", "word": "kalte", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Der süße Apfel schmeckt.", "word": "süße", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die saure Zitrone ist gelb.", "word": "saure", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Das harte Brot liegt da.", "word": "harte", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die weiche Butter ist gelb.", "word": "weiche", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Der dicke Käse schmeckt.", "word": "dicke", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Das dünne Blatt fällt.", "word": "dünne", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die lange Schlange kriecht.", "word": "lange", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Der kurze Stift schreibt.", "word": "kurze", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Das breite Fenster ist offen.", "word": "breite", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die enge Tür geht auf.", "word": "enge", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Der laute Hund bellt.", "word": "laute", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die leise Katze schleicht.", "word": "leise", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Das bunte Bild hängt.", "word": "bunte", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die dunkle Nacht kommt.", "word": "dunkle", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Der helle Tag beginnt.", "word": "helle", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Das schwere Buch liegt.", "word": "schwere", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die leichte Feder fliegt.", "word": "leichte", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Der glatte Stein rollt.", "word": "glatte", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die raue Rinde kratzt.", "word": "raue", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Das saubere Auto glänzt.", "word": "saubere", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die schmutzige Hose liegt.", "word": "schmutzige", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Der trockene Sand rieselt.", "word": "trockene", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die nasse Wiese glänzt.", "word": "nasse", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Das fröhliche Kind lacht.", "word": "fröhliche", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die traurige Frau weint.", "word": "traurige", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Der müde Mann schläft.", "word": "müde", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die wache Eule schaut.", "word": "wache", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Das kranke Tier liegt.", "word": "kranke", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die gesunde Pflanze wächst.", "word": "gesunde", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]}
]

# Grade 2 Fill-Blank Examples - Complete (150 examples)
GRADE2_FILL_BLANK_COMPLETE = [
    # Simple sentence completion - Animals (30 examples)
    {"text": "Der ___ bellt laut.", "answer": "Hund", "options": ["Hund", "Katze", "Vogel"]},
    {"text": "Die ___ miaut leise.", "answer": "Katze", "options": ["Katze", "Hund", "Maus"]},
    {"text": "Der kleine ___ springt.", "answer": "Hase", "options": ["Hase", "Elefant", "Wal"]},
    {"text": "Das ___ schwimmt im Wasser.", "answer": "Pferd", "options": ["Pferd", "Fisch", "Auto"]},
    {"text": "Die ___ fliegt hoch.", "answer": "Biene", "options": ["Biene", "Schnecke", "Wurm"]},
    {"text": "Der ___ ist sehr groß.", "answer": "Elefant", "options": ["Elefant", "Käfer", "Maus"]},
    {"text": "Die ___ gibt Milch.", "answer": "Kuh", "options": ["Kuh", "Ziege", "Huhn"]},
    {"text": "Das ___ legt Eier.", "answer": "Huhn", "options": ["Huhn", "Pferd", "Hund"]},
    {"text": "Der ___ kräht am Morgen.", "answer": "Hahn", "options": ["Hahn", "Hund", "Frosch"]},
    {"text": "Die ___ schwimmt im Teich.", "answer": "Ente", "options": ["Ente", "Katze", "Spinne"]},
    {"text": "Der ___ quakt laut.", "answer": "Frosch", "options": ["Frosch", "Vogel", "Hund"]},
    {"text": "Die ___ kriecht langsam.", "answer": "Schnecke", "options": ["Schnecke", "Hase", "Pferd"]},
    {"text": "Der ___ sammelt Nüsse.", "answer": "Eichhörnchen", "options": ["Eichhörnchen", "Fisch", "Vogel"]},
    {"text": "Die ___ baut ein Netz.", "answer": "Spinne", "options": ["Spinne", "Biene", "Käfer"]},
    {"text": "Der ___ hat Stacheln.", "answer": "Igel", "options": ["Igel", "Hase", "Kätzchen"]},
    {"text": "Das ___ hat einen Rüssel.", "answer": "Schwein", "options": ["Schwein", "Hund", "Katze"]},
    {"text": "Die ___ macht Wolle.", "answer": "Schaf", "options": ["Schaf", "Kuh", "Ziege"]},
    {"text": "Der ___ ist schwarz-weiß.", "answer": "Zebra", "options": ["Zebra", "Löwe", "Tiger"]},
    {"text": "Die ___ hat einen langen Hals.", "answer": "Giraffe", "options": ["Giraffe", "Maus", "Igel"]},
    {"text": "Der ___ brüllt laut.", "answer": "Löwe", "options": ["Löwe", "Maus", "Käfer"]},
    {"text": "Das ___ lebt im Wasser.", "answer": "Krokodil", "options": ["Krokodil", "Hund", "Katze"]},
    {"text": "Die ___ hopst im Wald.", "answer": "Reh", "options": ["Reh", "Fisch", "Vogel"]},
    {"text": "Der ___ ist rot.", "answer": "Fuchs", "options": ["Fuchs", "Bär", "Wolf"]},
    {"text": "Die ___ fliegt nachts.", "answer": "Eule", "options": ["Eule", "Hund", "Katze"]},
    {"text": "Der ___ kann sprechen.", "answer": "Papagei", "options": ["Papagei", "Fisch", "Maus"]},
    {"text": "Die ___ macht Honig.", "answer": "Biene", "options": ["Biene", "Fliege", "Käfer"]},
    {"text": "Der ___ frisst Blätter.", "answer": "Hirsch", "options": ["Hirsch", "Löwe", "Hai"]},
    {"text": "Das ___ wälzt sich im Schlamm.", "answer": "Schwein", "options": ["Schwein", "Katze", "Vogel"]},
    {"text": "Die ___ trägt ihre Babys im Beutel.", "answer": "Känguru", "options": ["Känguru", "Kuh", "Ziege"]},
    {"text": "Der ___ ist der König der Tiere.", "answer": "Löwe", "options": ["Löwe", "Hase", "Maus"]},

    # Daily activities (30 examples)
    {"text": "Mama ___ in der Küche.", "answer": "kocht", "options": ["kocht", "singt", "tanzt"]},
    {"text": "Papa ___ die Zeitung.", "answer": "liest", "options": ["liest", "isst", "trinkt"]},
    {"text": "Ich ___ zur Schule.", "answer": "gehe", "options": ["gehe", "fahre", "fliege"]},
    {"text": "Wir ___ zusammen.", "answer": "essen", "options": ["essen", "schlafen", "weinen"]},
    {"text": "Die Kinder ___ im Garten.", "answer": "spielen", "options": ["spielen", "kochen", "arbeiten"]},
    {"text": "Oma ___ eine Geschichte.", "answer": "erzählt", "options": ["erzählt", "singt", "tanzt"]},
    {"text": "Der Lehrer ___ an der Tafel.", "answer": "schreibt", "options": ["schreibt", "kocht", "schläft"]},
    {"text": "Ich ___ meine Zähne.", "answer": "putze", "options": ["putze", "wasche", "kämme"]},
    {"text": "Wir ___ ein Lied.", "answer": "singen", "options": ["singen", "essen", "trinken"]},
    {"text": "Papa ___ das Auto.", "answer": "wäscht", "options": ["wäscht", "kocht", "liest"]},
    {"text": "Mama ___ die Wäsche.", "answer": "hängt", "options": ["hängt", "singt", "tanzt"]},
    {"text": "Ich ___ im Bett.", "answer": "schlafe", "options": ["schlafe", "koche", "arbeite"]},
    {"text": "Der Hund ___ Gassi.", "answer": "geht", "options": ["geht", "kocht", "liest"]},
    {"text": "Wir ___ Fernsehen.", "answer": "schauen", "options": ["schauen", "kochen", "schlafen"]},
    {"text": "Opa ___ im Garten.", "answer": "arbeitet", "options": ["arbeitet", "schläft", "weint"]},
    {"text": "Die Familie ___ zusammen.", "answer": "frühstückt", "options": ["frühstückt", "schläft", "arbeitet"]},
    {"text": "Ich ___ mein Zimmer.", "answer": "räume", "options": ["räume", "koche", "singe"]},
    {"text": "Papa ___ zur Arbeit.", "answer": "fährt", "options": ["fährt", "schläft", "kocht"]},
    {"text": "Mama ___ Blumen.", "answer": "gießt", "options": ["gießt", "isst", "trinkt"]},
    {"text": "Wir ___ einen Kuchen.", "answer": "backen", "options": ["backen", "schlafen", "weinen"]},
    {"text": "Ich ___ Hausaufgaben.", "answer": "mache", "options": ["mache", "schlafe", "weine"]},
    {"text": "Der Postbote ___ Briefe.", "answer": "bringt", "options": ["bringt", "kocht", "schläft"]},
    {"text": "Wir ___ Musik.", "answer": "hören", "options": ["hören", "essen", "schlafen"]},
    {"text": "Ich ___ ein Bild.", "answer": "male", "options": ["male", "koche", "schlafe"]},
    {"text": "Papa ___ den Rasen.", "answer": "mäht", "options": ["mäht", "kocht", "schläft"]},
    {"text": "Mama ___ Kaffee.", "answer": "trinkt", "options": ["trinkt", "schläft", "weint"]},
    {"text": "Wir ___ spazieren.", "answer": "gehen", "options": ["gehen", "kochen", "schlafen"]},
    {"text": "Ich ___ ein Buch.", "answer": "lese", "options": ["lese", "koche", "weine"]},
    {"text": "Die Großeltern ___ zu Besuch.", "answer": "kommen", "options": ["kommen", "kochen", "schlafen"]},
    {"text": "Wir ___ gemeinsam.", "answer": "lachen", "options": ["lachen", "weinen", "schlafen"]},

    # Food and meals (30 examples)  
    {"text": "Zum Frühstück esse ich ___.", "answer": "Brot", "options": ["Brot", "Suppe", "Fisch"]},
    {"text": "Die ___ ist rot und rund.", "answer": "Tomate", "options": ["Tomate", "Banane", "Gurke"]},
    {"text": "Ich trinke gerne ___.", "answer": "Milch", "options": ["Milch", "Brot", "Käse"]},
    {"text": "Der ___ ist gelb und krumm.", "answer": "Apfel", "options": ["Apfel", "Banane", "Orange"]},
    {"text": "Zum Mittag gibt es ___.", "answer": "Suppe", "options": ["Suppe", "Milch", "Wasser"]},
    {"text": "Die ___ ist süß und rot.", "answer": "Erdbeere", "options": ["Erdbeere", "Zitrone", "Zwiebel"]},
    {"text": "Ich esse gern ___.", "answer": "Schokolade", "options": ["Schokolade", "Seife", "Papier"]},
    {"text": "Die ___ schwimmt im Wasser.", "answer": "Ente", "options": ["Ente", "Kartoffel", "Fisch"]},
    {"text": "Mutter backt einen ___.", "answer": "Kuchen", "options": ["Kuchen", "Fisch", "Ball"]},
    {"text": "Der ___ ist weiß und rund.", "answer": "Käse", "options": ["Käse", "Apfel", "Ball"]},
    {"text": "Ich trinke heißen ___.", "answer": "Tee", "options": ["Tee", "Eis", "Salat"]},
    {"text": "Die ___ ist orange.", "answer": "Orange", "options": ["Orange", "Apfel", "Traube"]},
    {"text": "Zum Abendbrot essen wir ___.", "answer": "Brot", "options": ["Brot", "Eis", "Bonbon"]},
    {"text": "Der ___ ist braun und süß.", "answer": "Zucker", "options": ["Zucker", "Salz", "Pfeffer"]},
    {"text": "Ich mag keine ___.", "answer": "Zwiebeln", "options": ["Zwiebeln", "Äpfel", "Bonbons"]},
    {"text": "Die ___ ist grün und lang.", "answer": "Gurke", "options": ["Gurke", "Tomate", "Orange"]},
    {"text": "Papa grillt ___.", "answer": "Würstchen", "options": ["Würstchen", "Eis", "Bonbons"]},
    {"text": "Die ___ wächst unter der Erde.", "answer": "Kartoffel", "options": ["Kartoffel", "Apfel", "Traube"]},
    {"text": "Ich esse ___ mit Honig.", "answer": "Brot", "options": ["Brot", "Fleisch", "Fisch"]},
    {"text": "Die ___ ist sauer und gelb.", "answer": "Zitrone", "options": ["Zitrone", "Orange", "Banane"]},
    {"text": "Oma kocht eine ___.", "answer": "Suppe", "options": ["Suppe", "Torte", "Pizza"]},
    {"text": "Der ___ kommt von der Kuh.", "answer": "Käse", "options": ["Käse", "Fisch", "Huhn"]},
    {"text": "Ich nasche gern ___.", "answer": "Bonbons", "options": ["Bonbons", "Zwiebeln", "Salz"]},
    {"text": "Die ___ hängen am Baum.", "answer": "Äpfel", "options": ["Äpfel", "Fische", "Steine"]},
    {"text": "Zum Trinken nehme ich ___.", "answer": "Wasser", "options": ["Wasser", "Brot", "Kuchen"]},
    {"text": "Der ___ schwimmt im Meer.", "answer": "Fisch", "options": ["Fisch", "Apfel", "Brot"]},
    {"text": "Ich esse ___ zum Nachtisch.", "answer": "Eis", "options": ["Eis", "Suppe", "Salat"]},
    {"text": "Die ___ ist hart und braun.", "answer": "Nuss", "options": ["Nuss", "Tomate", "Traube"]},
    {"text": "Papa kauft frisches ___.", "answer": "Brot", "options": ["Brot", "Wasser", "Luft"]},
    {"text": "Die ___ schmecken süß.", "answer": "Trauben", "options": ["Trauben", "Zwiebeln", "Zitronen"]},

    # Home and family (30 examples)
    {"text": "Ich wohne in einem ___.", "answer": "Haus", "options": ["Haus", "Auto", "Baum"]},
    {"text": "Mein ___ ist sehr groß.", "answer": "Zimmer", "options": ["Zimmer", "Apfel", "Ball"]},
    {"text": "Die ___ ist aus Holz.", "answer": "Tür", "options": ["Tür", "Milch", "Wasser"]},
    {"text": "Ich schlafe in meinem ___.", "answer": "Bett", "options": ["Bett", "Auto", "Garten"]},
    {"text": "Der ___ steht in der Küche.", "answer": "Tisch", "options": ["Tisch", "Baum", "Ball"]},
    {"text": "Meine ___ kocht das Essen.", "answer": "Mutter", "options": ["Mutter", "Katze", "Puppe"]},
    {"text": "Der ___ arbeitet im Büro.", "answer": "Vater", "options": ["Vater", "Hund", "Ball"]},
    {"text": "Meine ___ ist sehr alt.", "answer": "Oma", "options": ["Oma", "Puppe", "Katze"]},
    {"text": "Der ___ erzählt Geschichten.", "answer": "Opa", "options": ["Opa", "Hund", "Ball"]},
    {"text": "Mein ___ spielt mit mir.", "answer": "Bruder", "options": ["Bruder", "Baum", "Auto"]},
    {"text": "Meine ___ hilft mir.", "answer": "Schwester", "options": ["Schwester", "Puppe", "Blume"]},
    {"text": "Wir sitzen auf dem ___.", "answer": "Sofa", "options": ["Sofa", "Baum", "Auto"]},
    {"text": "Die ___ hängt an der Wand.", "answer": "Lampe", "options": ["Lampe", "Katze", "Milch"]},
    {"text": "Ich schaue durch das ___.", "answer": "Fenster", "options": ["Fenster", "Buch", "Essen"]},
    {"text": "Der ___ liegt auf dem Boden.", "answer": "Teppich", "options": ["Teppich", "Himmel", "Vogel"]},
    {"text": "Ich hänge meine Jacke in den ___.", "answer": "Schrank", "options": ["Schrank", "Garten", "Himmel"]},
    {"text": "Die ___ tickt laut.", "answer": "Uhr", "options": ["Uhr", "Katze", "Blume"]},
    {"text": "Ich schaue ___.", "answer": "Fernsehen", "options": ["Fernsehen", "Brot", "Milch"]},
    {"text": "Das ___ steht im Wohnzimmer.", "answer": "Sofa", "options": ["Sofa", "Auto", "Pferd"]},
    {"text": "Ich wasche mich im ___.", "answer": "Bad", "options": ["Bad", "Garten", "Auto"]},
    {"text": "Die ___ steht in der Küche.", "answer": "Spülmaschine", "options": ["Spülmaschine", "Katze", "Blume"]},
    {"text": "Ich lege mich aufs ___.", "answer": "Bett", "options": ["Bett", "Auto", "Baum"]},
    {"text": "Der ___ wärmt das Haus.", "answer": "Ofen", "options": ["Ofen", "Kühlschrank", "Ball"]},
    {"text": "Ich stelle die Blumen in die ___.", "answer": "Vase", "options": ["Vase", "Pfanne", "Tasche"]},
    {"text": "Das ___ hängt im Flur.", "answer": "Bild", "options": ["Bild", "Auto", "Fisch"]},
    {"text": "Ich öffne die ___ mit dem Schlüssel.", "answer": "Tür", "options": ["Tür", "Katze", "Milch"]},
    {"text": "Der ___ kühlt das Essen.", "answer": "Kühlschrank", "options": ["Kühlschrank", "Ofen", "Bett"]},
    {"text": "Ich sitze am ___.", "answer": "Tisch", "options": ["Tisch", "Himmel", "Baum"]},
    {"text": "Die ___ brennt hell.", "answer": "Kerze", "options": ["Kerze", "Katze", "Milch"]},
    {"text": "Ich räume mein ___ auf.", "answer": "Zimmer", "options": ["Zimmer", "Auto", "Fisch"]},

    # Colors and descriptions (30 examples)
    {"text": "Die Sonne ist ___.", "answer": "gelb", "options": ["gelb", "blau", "grün"]},
    {"text": "Das Gras ist ___.", "answer": "grün", "options": ["grün", "rot", "gelb"]},
    {"text": "Der Himmel ist ___.", "answer": "blau", "options": ["blau", "rot", "gelb"]},
    {"text": "Die Tomate ist ___.", "answer": "rot", "options": ["rot", "blau", "grün"]},
    {"text": "Der Schnee ist ___.", "answer": "weiß", "options": ["weiß", "schwarz", "rot"]},
    {"text": "Die Nacht ist ___.", "answer": "dunkel", "options": ["dunkel", "hell", "bunt"]},
    {"text": "Der Elefant ist ___.", "answer": "groß", "options": ["groß", "klein", "winzig"]},
    {"text": "Die Maus ist ___.", "answer": "klein", "options": ["klein", "groß", "riesig"]},
    {"text": "Der Honig ist ___.", "answer": "süß", "options": ["süß", "sauer", "bitter"]},
    {"text": "Die Zitrone ist ___.", "answer": "sauer", "options": ["sauer", "süß", "salzig"]},
    {"text": "Das Eis ist ___.", "answer": "kalt", "options": ["kalt", "heiß", "warm"]},
    {"text": "Die Suppe ist ___.", "answer": "heiß", "options": ["heiß", "kalt", "gefroren"]},
    {"text": "Der Stein ist ___.", "answer": "hart", "options": ["hart", "weich", "flüssig"]},
    {"text": "Das Kissen ist ___.", "answer": "weich", "options": ["weich", "hart", "spitz"]},
    {"text": "Der Bleistift ist ___.", "answer": "lang", "options": ["lang", "kurz", "rund"]},
    {"text": "Der Ball ist ___.", "answer": "rund", "options": ["rund", "eckig", "flach"]},
    {"text": "Das Buch ist ___.", "answer": "dick", "options": ["dick", "dünn", "flüssig"]},
    {"text": "Das Blatt ist ___.", "answer": "dünn", "options": ["dünn", "dick", "schwer"]},
    {"text": "Der Zucker ist ___.", "answer": "weiß", "options": ["weiß", "schwarz", "grün"]},
    {"text": "Die Kohle ist ___.", "answer": "schwarz", "options": ["schwarz", "weiß", "bunt"]},
    {"text": "Der Regenbogen ist ___.", "answer": "bunt", "options": ["bunt", "grau", "schwarz"]},
    {"text": "Das Gold ist ___.", "answer": "glänzend", "options": ["glänzend", "matt", "dunkel"]},
    {"text": "Die Seide ist ___.", "answer": "glatt", "options": ["glatt", "rau", "klebrig"]},
    {"text": "Die Rinde ist ___.", "answer": "rau", "options": ["rau", "glatt", "weich"]},
    {"text": "Der Honig ist ___.", "answer": "klebrig", "options": ["klebrig", "trocken", "hart"]},
    {"text": "Das Handtuch ist ___.", "answer": "trocken", "options": ["trocken", "nass", "gefroren"]},
    {"text": "Der Schwamm ist ___.", "answer": "nass", "options": ["nass", "trocken", "hart"]},
    {"text": "Der Ballon ist ___.", "answer": "leicht", "options": ["leicht", "schwer", "hart"]},
    {"text": "Der Koffer ist ___.", "answer": "schwer", "options": ["schwer", "leicht", "flüssig"]},
    {"text": "Die Musik ist ___.", "answer": "laut", "options": ["laut", "leise", "stumm"]}
]