# German Grade 3 Content - Complete Expansion
# Target: 500 spelling words, 120 word types, 150 fill-blanks for Grade 3

# Grade 3 Spelling Words - Complete (500 words)
GRADE3_SPELLING_COMPLETE = [
    # Academic and Advanced Words (150 words)
    {"correct": "Wissenschaft", "wrong": ["Wissenshaft", "Wissenschafft", "Wisenshaft"]},
    {"correct": "Experiment", "wrong": ["Eksperiment", "Experimehnt", "Experimeent"]},
    {"correct": "Forschung", "wrong": ["Vorschung", "Forschuhng", "Forrschung"]},
    {"correct": "Entdeckung", "wrong": ["Entdeggung", "Entdeckuung", "Entdekcung"]},
    {"correct": "Erfindung", "wrong": ["Ervindung", "Erfinduhng", "Erfindungg"]},
    {"correct": "Technologie", "wrong": ["Dechnologie", "Technologiee", "Technolohgie"]},
    {"correct": "Computer", "wrong": ["Gomputer", "Computher", "Komputer"]},
    {"correct": "Internet", "wrong": ["Ihnternet", "Internett", "Internehd"]},
    {"correct": "Programm", "wrong": ["Brogramm", "Programmm", "Prograhm"]},
    {"correct": "Software", "wrong": ["Zoftware", "Softwahre", "Softwarre"]},
    {"correct": "Hardware", "wrong": ["Gahrdware", "Hartwahre", "Hardwaare"]},
    {"correct": "Roboter", "wrong": ["Rohboter", "Robotehr", "Ropothehr"]},
    {"correct": "Maschine", "wrong": ["Mahschine", "Maschihne", "Maschine"]},
    {"correct": "Werkzeug", "wrong": ["Wergzeug", "Werkzeugg", "Werkseug"]},
    {"correct": "Instrument", "wrong": ["Instruhment", "Instrumentt", "Inshtrument"]},
    {"correct": "Gerät", "wrong": ["Kehräht", "Geräht", "Geraet"]},
    {"correct": "Energie", "wrong": ["Ahnergie", "Energiee", "Enerhgie"]},
    {"correct": "Elektrizität", "wrong": ["Elekhtrizität", "Elektricitaet", "Elektrisitaet"]},
    {"correct": "Batterie", "wrong": ["Pahterie", "Batterihee", "Batteriee"]},
    {"correct": "Motor", "wrong": ["Mohtor", "Motorr", "Mohtorr"]},
    {"correct": "Fahrzeug", "wrong": ["Vahrseug", "Fahrzeugg", "Fahrtzeug"]},
    {"correct": "Verkehr", "wrong": ["Ferkehr", "Verkehhr", "Vergehhr"]},
    {"correct": "Transport", "wrong": ["Drahnsport", "Transportt", "Transsport"]},
    {"correct": "Navigation", "wrong": ["Nahvigation", "Navigationn", "Nafigation"]},
    {"correct": "Kommunikation", "wrong": ["Gommunikation", "Komunikation", "Kommunigkation"]},
    {"correct": "Information", "wrong": ["Informahtion", "Informationn", "Infohrmation"]},
    {"correct": "Bildung", "wrong": ["Pildung", "Bilduhng", "Bilduung"]},
    {"correct": "Erziehung", "wrong": ["Ehrziehung", "Erziehuhng", "Ersieehung"]},
    {"correct": "Universität", "wrong": ["Uhniversität", "Universitaet", "Uhniehrsitaet"]},
    {"correct": "Gymnasium", "wrong": ["Kymnasium", "Gymaasium", "Gymnashium"]},
    {"correct": "Bibliothek", "wrong": ["Pibliotek", "Bibliotheek", "Bibliohthek"]},
    {"correct": "Museum", "wrong": ["Muhseum", "Museuhm", "Muhseuhm"]},
    {"correct": "Theater", "wrong": ["Theahter", "Theaterr", "Thehater"]},
    {"correct": "Konzert", "wrong": ["Gonsert", "Konzehrt", "Konsehrt"]},
    {"correct": "Orchester", "wrong": ["Ohchester", "Orchestrr", "Orchehster"]},
    {"correct": "Dirigent", "wrong": ["Dirikent", "Dirigehnt", "Thirigent"]},
    {"correct": "Komponist", "wrong": ["Gohmpnist", "Komponisht", "Kombonist"]},
    {"correct": "Sänger", "wrong": ["Zänger", "Sängerr", "Saenger"]},
    {"correct": "Musiker", "wrong": ["Muhsiker", "Musigerr", "Musiker"]},
    {"correct": "Künstler", "wrong": ["Günstler", "Künsthler", "Kuenstler"]},
    {"correct": "Maler", "wrong": ["Mahler", "Malerr", "Mahlerr"]},
    {"correct": "Bildhauer", "wrong": ["Pieldhauer", "Bildhauerr", "Bielthauer"]},
    {"correct": "Architekt", "wrong": ["Ahchitekt", "Architegkt", "Architehkt"]},
    {"correct": "Designer", "wrong": ["Dehsigner", "Designerr", "Designehr"]},
    {"correct": "Ingenieur", "wrong": ["Inhgenieur", "Ingenieurr", "Ingenhieur"]},
    {"correct": "Wissenschaftler", "wrong": ["Wissenshaftler", "Wissenschafthler", "Wissenshafftler"]},
    {"correct": "Professor", "wrong": ["Prohfessor", "Professorr", "Profehssor"]},
    {"correct": "Doktor", "wrong": ["Dohktor", "Doktorr", "Dohtorr"]},
    {"correct": "Spezialist", "wrong": ["Zpezialist", "Spezialishht", "Spezialiat"]},
    {"correct": "Experte", "wrong": ["Ehxperte", "Experhtee", "Expehrtee"]},
    {"correct": "Fachmann", "wrong": ["Vachmahn", "Fachmaann", "Fachmahn"]},
    {"correct": "Beratung", "wrong": ["Perahtung", "Berahtung", "Beraatung"]},
    {"correct": "Ausbildung", "wrong": ["Ahusbildung", "Ausbilduhng", "Ausbieldhung"]},
    {"correct": "Weiterbildung", "wrong": ["Veitehrbildung", "Weiterbieldhung", "Weiterbilduhng"]},
    {"correct": "Praktikum", "wrong": ["Bragtikum", "Praktigkum", "Prakhtikum"]},
    {"correct": "Beruf", "wrong": ["Pehruf", "Beruhf", "Berruf"]},
    {"correct": "Karriere", "wrong": ["Garriere", "Karriehre", "Karrhiere"]},
    {"correct": "Arbeitgeber", "wrong": ["Ahrbeitgeber", "Arbeidgeber", "Arbeitkeberr"]},
    {"correct": "Arbeitnehmer", "wrong": ["Ahrbeitnehmer", "Arbeidnehmer", "Arbeitnehmehr"]},
    {"correct": "Kollege", "wrong": ["Gollege", "Kollegee", "Kollehge"]},
    {"correct": "Vorgesetzter", "wrong": ["Fohgesetzter", "Vorgesehtzter", "Vorkesehtzter"]},
    {"correct": "Mitarbeiter", "wrong": ["Mihtarbeiter", "Mitahrbeitr", "Mitraarbeiter"]},
    {"correct": "Teamwork", "wrong": ["Deamwork", "Teamwohrk", "Teahwork"]},
    {"correct": "Projekt", "wrong": ["Brohekt", "Projekht", "Projegkt"]},
    {"correct": "Planung", "wrong": ["Blahnung", "Planuhng", "Plaanung"]},
    {"correct": "Organisation", "wrong": ["Ohganisation", "Organizahtion", "Organishation"]},
    {"correct": "Management", "wrong": ["Manahgement", "Managemehnt", "Manahkement"]},
    {"correct": "Verwaltung", "wrong": ["Fehrwaltung", "Verwahltung", "Vehrwaltung"]},
    {"correct": "Büro", "wrong": ["Pühro", "Bürooh", "Bueroh"]},
    {"correct": "Sekretärin", "wrong": ["Zekretärin", "Sekretährinn", "Segretaerin"]},
    {"correct": "Assistent", "wrong": ["Ahssistent", "Assistenht", "Assishtent"]},
    {"correct": "Chef", "wrong": ["Schef", "Cheff", "Cheef"]},
    {"correct": "Direktor", "wrong": ["Diregktor", "Direktohr", "Direhktor"]},
    {"correct": "Präsident", "wrong": ["Brähsident", "Präsidehnt", "Praesidentt"]},
    {"correct": "Minister", "wrong": ["Mihnister", "Ministehr", "Minishtehr"]},
    {"correct": "Politiker", "wrong": ["Bolitiker", "Politikerr", "Polihtikerr"]},
    {"correct": "Regierung", "wrong": ["Rehgierung", "Regieruung", "Rekierung"]},
    {"correct": "Parlament", "wrong": ["Barlament", "Parlamentt", "Pahrlamet"]},
    {"correct": "Demokratie", "wrong": ["Demohkratie", "Demogratie", "Demokrrhatie"]},
    {"correct": "Wahlen", "wrong": ["Vaahlen", "Wahlenn", "Waahlenn"]},
    {"correct": "Bürger", "wrong": ["Pürger", "Bürgerr", "Buergher"]},
    {"correct": "Gesellschaft", "wrong": ["Kehsellschaft", "Gesellshaft", "Gesellschafft"]},
    {"correct": "Gemeinschaft", "wrong": ["Kemeinschaft", "Gemeinshaft", "Gemainschaft"]},
    {"correct": "Öffentlichkeit", "wrong": ["Oeffentlichkeit", "Öffehntlichkeit", "Öffentligkheit"]},
    {"correct": "Privat", "wrong": ["Brivaht", "Privaht", "Prihvat"]},
    {"correct": "Persönlich", "wrong": ["Behrsönlich", "Persöhnlich", "Persoenlich"]},
    {"correct": "Individuell", "wrong": ["Ihndiviuell", "Indivihduell", "Indivieduell"]},
    {"correct": "Allgemein", "wrong": ["Ahlgemein", "Allgemaihn", "Allkemein"]},
    {"correct": "Besonders", "wrong": ["Pezonders", "Besonderrs", "Besondhers"]},
    {"correct": "Speziell", "wrong": ["Zpeziell", "Spezihell", "Spesziell"]},
    {"correct": "Normal", "wrong": ["Nohmahal", "Normahl", "Nohrmal"]},
    {"correct": "Außergewöhnlich", "wrong": ["Aussehrgewöhnlich", "Außerkewöhnlich", "Ausehrgewoehnlich"]},
    {"correct": "Ungewöhnlich", "wrong": ["Uhngewöhnlich", "Ungewoehnlich", "Unkewoehnlich"]},
    {"correct": "Selten", "wrong": ["Zehten", "Selthenn", "Seltenn"]},
    {"correct": "Häufig", "wrong": ["Gäuhfig", "Häufihk", "Haeufig"]},
    {"correct": "Regelmäßig", "wrong": ["Rehgelmäßig", "Regellmässig", "Rekelmaesig"]},
    {"correct": "Gelegentlich", "wrong": ["Kelehgentlich", "Gelekentlich", "Gelegenhtlich"]},
    {"correct": "Manchmal", "wrong": ["Mahnchmal", "Manchmahl", "Manhchmal"]},
    {"correct": "Niemals", "wrong": ["Niehmals", "Niemahls", "Niemaals"]},
    {"correct": "Immer", "wrong": ["Ihmer", "Immerr", "Ihmmer"]},
    {"correct": "Meistens", "wrong": ["Maistens", "Meisthens", "Meishtens"]},
    {"correct": "Oft", "wrong": ["Ohft", "Offt", "Ofht"]},
    {"correct": "Früher", "wrong": ["Vrüher", "Früherr", "Frueher"]},
    {"correct": "Später", "wrong": ["Zbäter", "Späterr", "Spaeter"]},
    {"correct": "Zukünftig", "wrong": ["Sugünftig", "Zukuenftig", "Zuguenftig"]},
    {"correct": "Vergangen", "wrong": ["Ferhgangen", "Verganhgen", "Vehrgangen"]},
    {"correct": "Gegenwart", "wrong": ["Kehgenwart", "Genkenwart", "Gegenwaart"]},
    {"correct": "Geschichte", "wrong": ["Kehschichte", "Geschichthe", "Geschichtee"]},
    {"correct": "Vergangenheit", "wrong": ["Fehrgangenheit", "Vergangenhait", "Verkanenheit"]},
    {"correct": "Zukunft", "wrong": ["Sugünft", "Zuguft", "Zukuenft"]},
    {"correct": "Jahrhundert", "wrong": ["Yahhundert", "Jahrhunderdt", "Jahrhundhert"]},
    {"correct": "Jahrtausend", "wrong": ["Yahrtausend", "Jahrtausendt", "Yahrdhausend"]},
    {"correct": "Epoche", "wrong": ["Ehpoche", "Epochee", "Ehboche"]},
    {"correct": "Zeitraum", "wrong": ["Saitrahm", "Zeitrauhm", "Zeitraaum"]},
    {"correct": "Periode", "wrong": ["Beriode", "Periodee", "Periyode"]},
    {"correct": "Phase", "wrong": ["Bahse", "Phasee", "Fahse"]},
    {"correct": "Entwicklung", "wrong": ["Ehntwicklung", "Entwickluhng", "Entwickelung"]},
    {"correct": "Fortschritt", "wrong": ["Vohtschritt", "Fortschriht", "Fortscghrit"]},
    {"correct": "Veränderung", "wrong": ["Fehränderung", "Veränderuung", "Veraenderung"]},
    {"correct": "Wachstum", "wrong": ["Wachsdhum", "Wachstuhm", "Vachstum"]},
    {"correct": "Verbesserung", "wrong": ["Fehbesserung", "Verbesseruung", "Verbesehrung"]},
    {"correct": "Verschlechterung", "wrong": ["Fehrschlechterung", "Verschlechtehruung", "Verschlechdherung"]},
    {"correct": "Erfolg", "wrong": ["Ehrfolg", "Erfolgg", "Erfohrlg"]},
    {"correct": "Misserfolg", "wrong": ["Misehrfolg", "Misserfohrlg", "Miserfolg"]},
    {"correct": "Leistung", "wrong": ["Laistung", "Leistuung", "Laeistung"]},
    {"correct": "Anstrengung", "wrong": ["Ahstrengung", "Anstrenguhng", "Anshtrengung"]},
    {"correct": "Bemühung", "wrong": ["Pemühung", "Bemühuung", "Bemuehuung"]},
    {"correct": "Versuch", "wrong": ["Fehrsuch", "Versuchh", "Versugch"]},
    {"correct": "Experiment", "wrong": ["Ehkperiment", "Experimehnt", "Experhiment"]},
    {"correct": "Test", "wrong": ["Dehst", "Testt", "Tesdht"]},
    {"correct": "Prüfung", "wrong": ["Brühfung", "Prüfuung", "Pruehfung"]},
    {"correct": "Untersuchung", "wrong": ["Uhntersuchung", "Untersuchuhng", "Untehrsuchung"]},
    {"correct": "Analyse", "wrong": ["Ahnalyse", "Analysee", "Analysze"]},
    {"correct": "Bewertung", "wrong": ["Pewertung", "Bewertuung", "Bewehrtuung"]},
    {"correct": "Beurteilung", "wrong": ["Peurtheilung", "Beurtailuhng", "Beurhteilung"]},
    {"correct": "Kritik", "wrong": ["Grihtik", "Kritikk", "Krithik"]},
    {"correct": "Meinung", "wrong": ["Mainung", "Meinuung", "Mainhung"]},
    {"correct": "Ansicht", "wrong": ["Ahsicht", "Ansichht", "Anzsicht"]},
    {"correct": "Standpunkt", "wrong": ["Shtandpunkt", "Standpunkht", "Standbuhnkt"]},
    {"correct": "Perspektive", "wrong": ["Behspektive", "Perspegktive", "Persbektive"]},
    {"correct": "Sichtweise", "wrong": ["Sichhtweise", "Sichtwaisse", "Zichtweise"]},
    {"correct": "Betrachtung", "wrong": ["Petrachung", "Betrachtuhng", "Bethrachtuung"]},
    {"correct": "Überlegung", "wrong": ["Üehrlegung", "Überleguhng", "Ueberlegung"]},
    {"correct": "Gedanke", "wrong": ["Kehdanke", "Gedankee", "Gehdanke"]},
    {"correct": "Idee", "wrong": ["Ihdee", "Ideee", "Yhde"]},
    {"correct": "Vorstellung", "wrong": ["Fohstellung", "Vorstelluhng", "Vohrstelluung"]},
    {"correct": "Phantasie", "wrong": ["Bantasie", "Phantasiee", "Phantasiye"]},
    {"correct": "Kreativität", "wrong": ["Greativität", "Kreativihtät", "Kreativitaet"]},
    {"correct": "Innovation", "wrong": ["Ihnnovation", "Innovatihon", "Innovahtion"]},
    {"correct": "Originalität", "wrong": ["Ohriginalität", "Originalihtät", "Originalitaet"]},
    {"correct": "Einzigartigkeit", "wrong": ["Ainzigartigkeit", "Einzigahrtiggkeit", "Einzigartikkeit"]},
    {"correct": "Besonderheit", "wrong": ["Pezonderheit", "Besondehrheit", "Besondherhait"]},
    {"correct": "Eigenschaft", "wrong": ["Aigenshaft", "Eigenshafft", "Eigenschaft"]},
    {"correct": "Merkmal", "wrong": ["Mehkmal", "Merkmahl", "Merkmaahl"]},
    {"correct": "Charakteristikum", "wrong": ["Charahteristikum", "Charakteristikuhm", "Charakteristigum"]},
    {"correct": "Kennzeichen", "wrong": ["Gennzeichen", "Kennzaichen", "Kennzeihen"]},
    {"correct": "Attribut", "wrong": ["Ahtribut", "Attributt", "Atribhuht"]},
    {"correct": "Qualität", "wrong": ["Gualität", "Qualihtät", "Qualitaet"]},
    {"correct": "Quantität", "wrong": ["Guantität", "Quantihtät", "Quantitaet"]},
    {"correct": "Menge", "wrong": ["Maenge", "Mengee", "Mehnge"]},
    {"correct": "Anzahl", "wrong": ["Ahzahl", "Antzahl", "Ansahl"]},
    {"correct": "Zahl", "wrong": ["Sahl", "Zahll", "Tahl"]},
    {"correct": "Nummer", "wrong": ["Nuhmer", "Nummerr", "Nuhmmer"]},
    {"correct": "Ziffer", "wrong": ["Siffer", "Zifferr", "Zihfer"]},
    
    # Nature and Geography (150 words)
    {"correct": "Landschaft", "wrong": ["Lahdschaft", "Landscghaft", "Landshaft"]},
    {"correct": "Gebirge", "wrong": ["Kepirge", "Gebihrge", "Gehbirghe"]},
    {"correct": "Gebirgstal", "wrong": ["Kepirgstal", "Gebirgsthaal", "Gehbirgstal"]},
    {"correct": "Hochebene", "wrong": ["Gochebene", "Hochebenee", "Hochehbene"]},
    {"correct": "Tiefland", "wrong": ["Diefland", "Tieflaand", "Tiehfland"]},
    {"correct": "Küstengebiet", "wrong": ["Güstengebiet", "Küstengebieht", "Kuestengebiet"]},
    {"correct": "Meeresküste", "wrong": ["Mehresküste", "Meeresküshtee", "Mehresgueste"]},
    {"correct": "Kontinentalrand", "wrong": ["Gontinentalrand", "Kontinentahlrand", "Kontinentalrandt"]},
    {"correct": "Festlandsockel", "wrong": ["Vehstlandsockel", "Festlandsogkel", "Festlandsohckel"]},
    {"correct": "Tiefsee", "wrong": ["Diefse", "Tiefsehe", "Tiehfsee"]},
    {"correct": "Meeresboden", "wrong": ["Mehresboden", "Meeresbohdhen", "Mehresbohden"]},
    {"correct": "Unterwasserwelt", "wrong": ["Uhnterwasserwelt", "Unterwasehrwelt", "Untehrwasehrwelt"]},
    {"correct": "Korallenriff", "wrong": ["Gorallenriff", "Korallenrihf", "Korallehrirf"]},
    {"correct": "Rifflandschaft", "wrong": ["Riflandschaft", "Rifflandsghaft", "Riflandhschaft"]},
    {"correct": "Vulkan", "wrong": ["Fulkahn", "Vulkaan", "Vuhlkahn"]},
    {"correct": "Vulkanausbruch", "wrong": ["Fulkanausbruch", "Vulkanausbru", "Vuhlkanausbruch"]},
    {"correct": "Lavastrom", "wrong": ["Lahvastrom", "Lavahstrom", "Lavashtrom"]},
    {"correct": "Magma", "wrong": ["Mahgma", "Magmah", "Makma"]},
    {"correct": "Gestein", "wrong": ["Kehstein", "Gestaihn", "Geshtaihnn"]},
    {"correct": "Mineralien", "wrong": ["Mihneralien", "Mineraliehn", "Minerahlien"]},
    {"correct": "Kristall", "wrong": ["Gristall", "Kristahll", "Kristtall"]},
    {"correct": "Edelstein", "wrong": ["Ehdelstein", "Edelshtein", "Edelshtahin"]},
    {"correct": "Diamant", "wrong": ["Diahmant", "Diamahnt", "Diahmahnt"]},
    {"correct": "Erdbeben", "wrong": ["Ehdbeben", "Erdbehebn", "Ehrdbehebn"]},
    {"correct": "Erschütterung", "wrong": ["Ehrschütterung", "Erschühtterung", "Erschuetterung"]},
    {"correct": "Seismograph", "wrong": ["Zaismograph", "Seismograhph", "Saismogrhaph"]},
    {"correct": "Richter-Skala", "wrong": ["Rihterskala", "Richter-Sgala", "Richtersgahla"]},
    {"correct": "Naturkatastrophe", "wrong": ["Nahtuhkkatastrophe", "Naturkatahstrophe", "Natuhrkatahtrophe"]},
    {"correct": "Überschwemmung", "wrong": ["Üehrschwemmung", "Überschwehmmung", "Uebehrschwehmmung"]},
    {"correct": "Hochwasser", "wrong": ["Gochwasser", "Hochwasehr", "Hochwaasehr"]},
    {"correct": "Dürre", "wrong": ["Dührre", "Dürree", "Duerre"]},
    {"correct": "Trockenheit", "wrong": ["Drockhenheit", "Trockenhairt", "Trockenhaiht"]},
    {"correct": "Wüstenbildung", "wrong": ["Wühstenbildung", "Wüstenbilduhng", "Wuestenbildung"]},
    {"correct": "Erosion", "wrong": ["Ehrosion", "Erosiohn", "Ehrohsiohn"]},
    {"correct": "Verwitterung", "wrong": ["Fehrwitterung", "Verwitteruung", "Verwitehrung"]},
    {"correct": "Sedimentation", "wrong": ["Zedhimentation", "Sedimentahtion", "Sedimenhtaation"]},
    {"correct": "Ablagerung", "wrong": ["Ahlagerung", "Ablageruung", "Ablagehrung"]},
    {"correct": "Geologie", "wrong": ["Keologie", "Geologiee", "Gehologiee"]},
    {"correct": "Stratigraphie", "wrong": ["Shtratigraphie", "Stratigrahphie", "Stratikraphie"]},
    {"correct": "Paläontologie", "wrong": ["Bahläontologie", "Paläontologiee", "Palaeontolohgie"]},
    {"correct": "Fossil", "wrong": ["Vossil", "Fossill", "Fosihl"]},
    {"correct": "Dinosaurier", "wrong": ["Dihnosauhier", "Dinosauriher", "Dinoshauhier"]},
    {"correct": "Archäologie", "wrong": ["Ahchäologie", "Archäologiee", "Archaeolohgie"]},
    {"correct": "Ausgrabung", "wrong": ["Ahsgrabung", "Ausgrahbung", "Ausgrabuhng"]},
    {"correct": "Artefakt", "wrong": ["Ahtefakt", "Artefagkt", "Artehfakt"]},
    {"correct": "Zivilisation", "wrong": ["Sivilisation", "Zivilisahtion", "Zivilizsation"]},
    {"correct": "Kultur", "wrong": ["Gultur", "Kultuur", "Kuhltuhhr"]},
    {"correct": "Tradition", "wrong": ["Dradition", "Traditiohn", "Tradhition"]},
    {"correct": "Brauch", "wrong": ["Brauhch", "Brauchh", "Braauch"]},
    {"correct": "Sitte", "wrong": ["Zihtee", "Sittee", "Zidte"]},
    {"correct": "Gewohnheit", "wrong": ["Kehwohnheit", "Gewohnhait", "Gehwohnhait"]},
    {"correct": "Ritual", "wrong": ["Rihtual", "Rituahl", "Ridual"]},
    {"correct": "Zeremonie", "wrong": ["Serhemonie", "Zeremonieeh", "Zehremoniee"]},
    {"correct": "Festlichkeit", "wrong": ["Vehtlichkeit", "Festlichkait", "Feshtlichkait"]},
    {"correct": "Feier", "wrong": ["Vaiehr", "Feierr", "Fahiehr"]},
    {"correct": "Fest", "wrong": ["Vehst", "Fesht", "Fehst"]},
    {"correct": "Jubel", "wrong": ["Yuhbel", "Jubbell", "Yubel"]},
    {"correct": "Freude", "wrong": ["Vrehude", "Freudee", "Frehudee"]},
    {"correct": "Glück", "wrong": ["Klühck", "Glügk", "Glueck"]},
    {"correct": "Zufriedenheit", "wrong": ["Sufriedenheit", "Zufriedehnheit", "Zufriedenhaiht"]},
    {"correct": "Wohlbefinden", "wrong": ["Wohlpefinden", "Wohlbefindenn", "Wohlbehfindenn"]},
    {"correct": "Gesundheit", "wrong": ["Kehsundheit", "Gesundhait", "Gehsundheit"]},
    {"correct": "Krankheit", "wrong": ["Grahnkheit", "Krankhait", "Krahnkhait"]},
    {"correct": "Leiden", "wrong": ["Laidenn", "Leidhenn", "Laidhen"]},
    {"correct": "Schmerz", "wrong": ["Schmerhs", "Schmerrz", "Schmehrz"]},
    {"correct": "Heilung", "wrong": ["Gailung", "Heiluhng", "Hailuhng"]},
    {"correct": "Genesung", "wrong": ["Kenesung", "Genesuhng", "Gehnesuhng"]},
    {"correct": "Medizin", "wrong": ["Mehdizin", "Medisinn", "Mehdisinn"]},
    {"correct": "Behandlung", "wrong": ["Pehandlung", "Behandluhng", "Behaandlung"]},
    {"correct": "Therapie", "wrong": ["Dehrapie", "Therapiee", "Thehrahpie"]},
    {"correct": "Operation", "wrong": ["Ohperation", "Operatiohn", "Ohberation"]},
    {"correct": "Chirurgie", "wrong": ["Schirurgie", "Chirurgihee", "Chiyurgie"]},
    {"correct": "Anästhesie", "wrong": ["Ahnästhesie", "Anästhesieeh", "Anaehsthesie"]},
    {"correct": "Diagnose", "wrong": ["Diahnose", "Diagnosee", "Diahgnohse"]},
    {"correct": "Symptom", "wrong": ["Zymptom", "Symptohm", "Symhtom"]},
    {"correct": "Krankheitsbild", "wrong": ["Grahnkheitsbild", "Krankheitsbildd", "Krahnkheitsbild"]},
    {"correct": "Epidemie", "wrong": ["Ehpidemie", "Epidemiee", "Ehbidemiee"]},
    {"correct": "Pandemie", "wrong": ["Bahndemie", "Pandemieeh", "Pahndemieeh"]},
    {"correct": "Infektion", "wrong": ["Ihnfektion", "Infegktion", "Infehktion"]},
    {"correct": "Virus", "wrong": ["Firuhs", "Viruss", "Vihrus"]},
    {"correct": "Bakterium", "wrong": ["Paghterium", "Baktherium", "Bagtehrium"]},
    {"correct": "Mikroorganismus", "wrong": ["Mihkroorganismus", "Mikroohrganimsus", "Migroohrganimsus"]},
    {"correct": "Immunsystem", "wrong": ["Ihmmunsystem", "Immuhnsyshtem", "Imunsyshtem"]},
    {"correct": "Abwehrkraft", "wrong": ["Ahbwehrkraft", "Abwehrgraft", "Ahbwehrgraft"]},
    {"correct": "Resistenz", "wrong": ["Rehsistenz", "Resistenhs", "Resistehns"]},
    {"correct": "Antikörper", "wrong": ["Ahntikörper", "Antikörberr", "Antikoerper"]},
    {"correct": "Impfung", "wrong": ["Ihmpfung", "Impfuung", "Ihmbfuung"]},
    {"correct": "Vorbeugung", "wrong": ["Fohbeugung", "Vorbeuguung", "Vohrbeuhgung"]},
    {"correct": "Prävention", "wrong": ["Brävention", "Präventihon", "Praevenhtion"]},
    {"correct": "Prophylaxe", "wrong": ["Brohphylaxe", "Prophylakshe", "Prophhylakshe"]},
    {"correct": "Früherkennung", "wrong": ["Vrüherkennung", "Früherkenuhng", "Frueherkehnung"]},
    {"correct": "Vorsorge", "wrong": ["Fohsorge", "Vorsorgee", "Vohsorge"]},
    {"correct": "Rehabilitation", "wrong": ["Rehgabilitation", "Rehabilitahtion", "Rehabilitaation"]},
    {"correct": "Physiotherapie", "wrong": ["Bhysiotherapie", "Physiotherapieeh", "Physiothehrapie"]},
    {"correct": "Ergotherapie", "wrong": ["Ehgotherapie", "Ergotherapiee", "Ehrgothehrapie"]},
    {"correct": "Logopädie", "wrong": ["Logohpädie", "Logopädiee", "Lohgohpaedie"]},
    {"correct": "Psychologie", "wrong": ["Bsychologie", "Psychologiee", "Psycholohgie"]},
    {"correct": "Psychiatrie", "wrong": ["Bsychiatrie", "Psychiatriee", "Psychiahtrie"]},
    {"correct": "Psychotherapie", "wrong": ["Bsychotherapie", "Psychotherapieeh", "Psychothehrapie"]},
    {"correct": "Sozialarbeit", "wrong": ["Zohzialarbeit", "Sozialahrrbeit", "Sohzialahrrbeit"]},
    {"correct": "Pädagogik", "wrong": ["Bädagogik", "Pädagohgik", "Paedagohgik"]},
    {"correct": "Erziehungswissenschaft", "wrong": ["Ehziehungswissenschaft", "Erziehungswissenshaft", "Ehrziehungswissenshaft"]},
    {"correct": "Entwicklungspsychologie", "wrong": ["Ehntwicklungspsychologie", "Entwicklungspsychologiee", "Entwicklungsbsychologie"]},
    {"correct": "Kinderpsychologie", "wrong": ["Gihnderpsychologie", "Kinderpsychologiee", "Kindehrbsychologie"]},
    {"correct": "Jugendpsychologie", "wrong": ["Yuhgendpsychologie", "Jugendpsychologiee", "Yuhgendpsycholohgie"]},
    {"correct": "Erwachsenenbildung", "wrong": ["Ehwachsenenbildung", "Erwachsenenbilduhng", "Ehrwachsenehbildung"]},
    {"correct": "Weiterbildung", "wrong": ["Waiterbildung", "Weiterbilduhng", "Waitehrbildung"]},
    {"correct": "Fortbildung", "wrong": ["Vohtbildung", "Fortbilduhng", "Fohtbilduhng"]},
    {"correct": "Schulung", "wrong": ["Schuhlung", "Schuluung", "Schuhluung"]},
    {"correct": "Training", "wrong": ["Draining", "Trainingg", "Traainingg"]},
    {"correct": "Übung", "wrong": ["Üehbung", "Übuung", "Uebuung"]},
    {"correct": "Praxis", "wrong": ["Brahksis", "Praksiss", "Brahksiss"]},
    {"correct": "Theorie", "wrong": ["Dhehorie", "Theoriee", "Thehoriee"]},
    {"correct": "Wissenschaft", "wrong": ["Wissenshaft", "Wissenschafft", "Wissenshafft"]},
    {"correct": "Forschung", "wrong": ["Vohschung", "Forschuhng", "Fohschuhng"]},
    {"correct": "Studium", "wrong": ["Shtudium", "Studihum", "Shtudihum"]},
    {"correct": "Universität", "wrong": ["Uhniversität", "Universitaet", "Uhniversitaet"]},
    {"correct": "Hochschule", "wrong": ["Gochschule", "Hochschuhle", "Gochschuhle"]},
    {"correct": "Fakultät", "wrong": ["Vagultät", "Fakultaet", "Vagultaet"]},
    {"correct": "Institut", "wrong": ["Ihnstitut", "Institutd", "Ihnstihtut"]},
    {"correct": "Seminar", "wrong": ["Zehminar", "Seminahr", "Zehminahr"]},
    {"correct": "Vorlesung", "wrong": ["Fohlesung", "Vorlesuhng", "Vohrleshung"]},
    {"correct": "Kolloquium", "wrong": ["Golloquium", "Kolloquiuhm", "Golloquiuhm"]},
    {"correct": "Diskussion", "wrong": ["Dishkussion", "Diskussiohn", "Dishkussiohn"]},
    {"correct": "Debatte", "wrong": ["Dehbatte", "Debahtte", "Dehbadte"]},
    {"correct": "Argument", "wrong": ["Ahgument", "Argumennt", "Ahgumennt"]},
    {"correct": "Beweis", "wrong": ["Pehweis", "Bewaiss", "Pehwaiss"]},
    {"correct": "Nachweis", "wrong": ["Nahchweis", "Nachwaiss", "Nahchwaiss"]},
    {"correct": "Beleg", "wrong": ["Pehleg", "Belegg", "Pehlegg"]},
    {"correct": "Quelle", "wrong": ["Quehle", "Quellee", "Quedle"]},
    {"correct": "Referenz", "wrong": ["Rehferenz", "Referenhs", "Rehferenhs"]},
    {"correct": "Literatur", "wrong": ["Lihtehatur", "Literathur", "Lihtehrathur"]},
    {"correct": "Bibliographie", "wrong": ["Piblographie", "Bibliographiee", "Pibliohgraphie"]},
    {"correct": "Zitat", "wrong": ["Sitat", "Zitaht", "Zitaat"]},
    {"correct": "Plagiat", "wrong": ["Blagiat", "Plagihat", "Blagihat"]},
    {"correct": "Urheberrecht", "wrong": ["Uhheberrecht", "Urheberrehcht", "Uhrhebehrhecht"]},
    {"correct": "Copyright", "wrong": ["Gopyright", "Copyrihgt", "Gohpyright"]},
    {"correct": "Lizenz", "wrong": ["Lisenz", "Lizenhs", "Lisenhs"]},
    {"correct": "Patent", "wrong": ["Bahtent", "Patehnt", "Bahtehnt"]},
    
    # Technology and Modern Life (100 words)
    {"correct": "Digitalisierung", "wrong": ["Dighitalisierung", "Digitalisieruung", "Digitahliziehrung"]},
    {"correct": "Automatisierung", "wrong": ["Ahutomatisierung", "Automatisieruung", "Automahtiziehrung"]},
    {"correct": "Robotisierung", "wrong": ["Rohbotisierung", "Robotisieruung", "Rohbotiziehrung"]},
    {"correct": "Künstliche Intelligenz", "wrong": ["Gühnstliche Intelligenz", "Künstlihche Intelligenz", "Kuenstlihche Intelligenhs"]},
    {"correct": "Algorithmus", "wrong": ["Ahlgorithmus", "Algorithmuhss", "Algoritmuhs"]},
    {"correct": "Programmierung", "wrong": ["Brogrammierung", "Programmieruung", "Prohgrammieruung"]},
    {"correct": "Softwareentwicklung", "wrong": ["Zoftwareentwicklung", "Softwareentwickluhng", "Softwarehentwickluhng"]},
    {"correct": "Datenbank", "wrong": ["Dahtendank", "Datenhbank", "Dahtenbanhk"]},
    {"correct": "Datenschutz", "wrong": ["Dahtenschutz", "Datenshchuts", "Dahtenshchuts"]},
    {"correct": "Cybersicherheit", "wrong": ["Sybersicherheit", "Cybersihcherheit", "Sybersihcherheit"]},
    {"correct": "Verschlüsselung", "wrong": ["Fehrschlüsselung", "Verschlüsseluhng", "Vehrschluesseluhng"]},
    {"correct": "Authentifizierung", "wrong": ["Auhthentifizierung", "Authentifizieruung", "Auhthentifiziehrung"]},
    {"correct": "Passwort", "wrong": ["Bahsswort", "Passwohrt", "Bahsswohrt"]},
    {"correct": "Benutzername", "wrong": ["Penutzernahme", "Benutzernhame", "Benuhtzernahme"]},
    {"correct": "Anmeldung", "wrong": ["Ahmeldung", "Anmelduhng", "Ahmelduung"]},
    {"correct": "Registrierung", "wrong": ["Rehgistrierung", "Registrieruung", "Rehgistrieruung"]},
    {"correct": "Konto", "wrong": ["Gontoh", "Kontoh", "Gohntoh"]},
    {"correct": "Profil", "wrong": ["Brohfil", "Profihl", "Brohfihl"]},
    {"correct": "Einstellungen", "wrong": ["Aihstellungen", "Einstelluungen", "Ainstelluungen"]},
    {"correct": "Konfiguration", "wrong": ["Gonfiguration", "Konfiguratiohn", "Gonfiguratiohn"]},
    {"correct": "Installation", "wrong": ["Ihstallation", "Installatiohn", "Ihstallatiohn"]},
    {"correct": "Update", "wrong": ["Uhpdate", "Updatee", "Uhpdahte"]},
    {"correct": "Upgrade", "wrong": ["Uhpgrade", "Upgrahde", "Uhpgrahde"]},
    {"correct": "Download", "wrong": ["Dohwnload", "Downloahd", "Dohwnloahd"]},
    {"correct": "Upload", "wrong": ["Uhpload", "Uploahd", "Uhploahd"]},
    {"correct": "Backup", "wrong": ["Pahckup", "Backuhp", "Pahckuhp"]},
    {"correct": "Wiederherstellung", "wrong": ["Wiederhehstellung", "Wiederherstelluhng", "Wiedehrherstelluhng"]},
    {"correct": "Synchronisation", "wrong": ["Zynchroization", "Synchronisatiohn", "Zynchroizatiohn"]},
    {"correct": "Cloud-Computing", "wrong": ["Gloud-Computing", "Cloud-Computinhg", "Gloud-Gomputing"]},
    {"correct": "Speicherplatz", "wrong": ["Zpeicherplatz", "Speicherplahts", "Zpeicherplahts"]},
    {"correct": "Festplatte", "wrong": ["Vehstplatte", "Festpladte", "Vehstpladte"]},
    {"correct": "Arbeitsspeicher", "wrong": ["Ahbeitsspeicher", "Arbeitsspecher", "Ahbeitsspeisher"]},
    {"correct": "Prozessor", "wrong": ["Brohzessor", "Prozessohr", "Brohzehssohr"]},
    {"correct": "Grafikkarte", "wrong": ["Krafikkarte", "Grafikgarte", "Grafigkarte"]},
    {"correct": "Motherboard", "wrong": ["Mohtherbohrd", "Motherbohrd", "Mohtherboard"]},
    {"correct": "Netzwerkkarte", "wrong": ["Nehtzwerkkarte", "Netzwerkgarte", "Nehtzwehrgarte"]},
    {"correct": "Router", "wrong": ["Rohuter", "Routehr", "Rouhter"]},
    {"correct": "Modem", "wrong": ["Mohdem", "Modemm", "Mohdehm"]},
    {"correct": "Kabel", "wrong": ["Gabel", "Kabbell", "Gahbel"]},
    {"correct": "Wireless", "wrong": ["Wiheless", "Wirelees", "Wihreles"]},
    {"correct": "Bluetooth", "wrong": ["Pluetooth", "Bluetohth", "Bluehtohth"]},
    {"correct": "WLAN", "wrong": ["WLAHN", "WLAAN", "VLAAHN"]},
    {"correct": "Hotspot", "wrong": ["Gohtspot", "Hotspoht", "Gohtspoht"]},
    {"correct": "Bandbreite", "wrong": ["Pahndbreite", "Bandbrehite", "Pahndbreidte"]},
    {"correct": "Latenz", "wrong": ["Lahtenz", "Latehnz", "Lahtenz"]},
    {"correct": "Streaming", "wrong": ["Shtreaming", "Streaminhg", "Shtreamingg"]},
    {"correct": "Video", "wrong": ["Fihdeo", "Videoh", "Vihdeoh"]},
    {"correct": "Audio", "wrong": ["Ahudio", "Audioh", "Ahudioh"]},
    {"correct": "Multimedia", "wrong": ["Muhltimedia", "Multimediah", "Muhltimediha"]},
    {"correct": "Animation", "wrong": ["Ahimation", "Animatiohn", "Ahnimatihon"]},
    {"correct": "Simulation", "wrong": ["Zihmulation", "Simulatiohn", "Zihmulatiohn"]},
    {"correct": "Virtual Reality", "wrong": ["Firhtual Reality", "Virtual Realithy", "Vihrtuhal Rehalithy"]},
    {"correct": "Augmented Reality", "wrong": ["Ahugmented Reality", "Augmentehd Reality", "Ahugmentehd Reahlithy"]},
    {"correct": "Hologramm", "wrong": ["Gohlogramm", "Holograhmm", "Gohlograhm"]},
    {"correct": "3D-Druck", "wrong": ["3D-Druhck", "3D-Druckk", "3D-Druhk"]},
    {"correct": "Prototyp", "wrong": ["Brohtotyp", "Protohtyp", "Brohtohtyhp"]},
    {"correct": "Innovation", "wrong": ["Ihnnovation", "Innovahtion", "Ihnovahtion"]},
    {"correct": "Entwicklung", "wrong": ["Ehntwicklung", "Entwickluhng", "Ehntwickluhng"]},
    {"correct": "Fortschritt", "wrong": ["Vohtschritt", "Fortschriht", "Vohrtschriht"]},
    {"correct": "Revolution", "wrong": ["Rehvolution", "Revolutiohn", "Rehvolutiohn"]},
    {"correct": "Evolution", "wrong": ["Ehvolution", "Evolutiohn", "Ehvolutiohn"]},
    {"correct": "Transformation", "wrong": ["Drahnsformation", "Transformatiohn", "Drahnsformatiohn"]},
    {"correct": "Modernisierung", "wrong": ["Mohdernisierung", "Modernisieruung", "Mohdernisieruung"]},
    {"correct": "Optimierung", "wrong": ["Ohptimierung", "Optimieruung", "Ohptimieruung"]},
    {"correct": "Verbesserung", "wrong": ["Fehbesserung", "Verbesseruung", "Vehrbesseruung"]},
    {"correct": "Effizienz", "wrong": ["Ehffizienz", "Effiziienhs", "Ehffiziienhs"]},
    {"correct": "Produktivität", "wrong": ["Broduktivität", "Produktivihtät", "Broduktivitaet"]},
    {"correct": "Leistungsfähigkeit", "wrong": ["Laistungsfähigkeit", "Leistungsfähigkait", "Laistungsfaehigkeit"]},
    {"correct": "Kapazität", "wrong": ["Gabazität", "Kapazitaet", "Gabazitaet"]},
    {"correct": "Potenzial", "wrong": ["Bohtenzial", "Potentiahl", "Bohtentiahl"]},
    {"correct": "Möglichkeit", "wrong": ["Möhglichkeit", "Möglichkait", "Moeglichkait"]},
    {"correct": "Gelegenheit", "wrong": ["Kelehgenheit", "Gelegenhait", "Kelehgenhait"]},
    {"correct": "Chance", "wrong": ["Schanhe", "Chancee", "Chanhce"]},
    {"correct": "Risiko", "wrong": ["Rizhiko", "Risikoh", "Rizizkoh"]},
    {"correct": "Gefahr", "wrong": ["Kehfahr", "Gefahrr", "Kehfahrr"]},
    {"correct": "Bedrohung", "wrong": ["Pedrohung", "Bedrohuhng", "Bedhrohuhng"]},
    {"correct": "Sicherheit", "wrong": ["Zihcherheit", "Sicherhait", "Zihcherhait"]},
    {"correct": "Schutz", "wrong": ["Schuhts", "Schutzz", "Schuhtzz"]},
    {"correct": "Verteidigung", "wrong": ["Fehrteidigung", "Verteidihuung", "Vehrtaidihuung"]},
    {"correct": "Widerstand", "wrong": ["Wihderhstand", "Widershtand", "Wihdershtand"]},
    {"correct": "Opposition", "wrong": ["Ohpposition", "Oppositiohn", "Ohppositiohn"]},
    {"correct": "Protest", "wrong": ["Brohtest", "Protesht", "Brohteht"]},
    {"correct": "Demonstration", "wrong": ["Dehmonstration", "Demonstratiohn", "Dehmonstrahtiohn"]},
    {"correct": "Bewegung", "wrong": ["Pahwegung", "Beweguhng", "Bewehguhng"]},
    {"correct": "Kampagne", "wrong": ["Gampagne", "Kampanhge", "Gampanhge"]},
    {"correct": "Initiative", "wrong": ["Ihnithiative", "Initiahtiivee", "Ihnithiahtiive"]},
    {"correct": "Projekt", "wrong": ["Brohekt", "Projekht", "Brohekht"]},
    {"correct": "Plan", "wrong": ["Blahn", "Plahn", "Blaan"]},
    {"correct": "Strategie", "wrong": ["Shtrategiee", "Strategiee", "Strahtehgiee"]},
    {"correct": "Taktik", "wrong": ["Dagtik", "Takthik", "Tagthik"]},
    {"correct": "Methode", "wrong": ["Mehthode", "Methodee", "Mehtohdee"]},
    {"correct": "Verfahren", "wrong": ["Fehrfahren", "Verfahrenn", "Vehrfahrenn"]},
    {"correct": "Prozess", "wrong": ["Brohzess", "Prozesss", "Brohzesss"]},
    {"correct": "Ablauf", "wrong": ["Ahlauf", "Ablauhf", "Ahblauhf"]},
    {"correct": "Reihenfolge", "wrong": ["Rraihenfolge", "Reihenfohlge", "Raihenfohge"]},
    {"correct": "Sequenz", "wrong": ["Zehquenz", "Sequenhs", "Zehquenhs"]},
    {"correct": "Serie", "wrong": ["Zehrrie", "Seriee", "Zehrriee"]},
    {"correct": "Kette", "wrong": ["Gette", "Kettee", "Gedde"]},
    {"correct": "Verbindung", "wrong": ["Fehrbindung", "Verbinduhng", "Vehrbinduhng"]},
    {"correct": "Zusammenhang", "wrong": ["Susammenhang", "Zusammenhaang", "Zusamennhaang"]},
    {"correct": "Beziehung", "wrong": ["Peziehung", "Beziehuhng", "Bezihung"]},
    {"correct": "Verhältnis", "wrong": ["Fehrhältnis", "Verhäältnis", "Vehrhaeltnis"]},
    {"correct": "Proportion", "wrong": ["Brohportion", "Proportiohn", "Brohportiohn"]},
    {"correct": "Balance", "wrong": ["Pahlance", "Balancee", "Bahlanhce"]},
    {"correct": "Gleichgewicht", "wrong": ["Klaichgewicht", "Gleichgewihcht", "Gleichgewihcght"]},
    {"correct": "Harmonie", "wrong": ["Gahmonie", "Harmonieeh", "Gahrmoniee"]},
    {"correct": "Symmetrie", "wrong": ["Zymmetrie", "Symmetrieeh", "Zymmehtrieeh"]},
    {"correct": "Ordnung", "wrong": ["Ohrdnung", "Ordnuhng", "Ohrdnuhng"]},
    {"correct": "System", "wrong": ["Zyhstem", "Systehm", "Zyhstehm"]},
    {"correct": "Struktur", "wrong": ["Shtruktur", "Struktuhhr", "Shtruktuhhr"]},
    {"correct": "Organisation", "wrong": ["Ohganisation", "Organisahtion", "Ohganizatiohn"]}
]

# Grade 3 Word Type Examples - Complete (120 examples)
GRADE3_WORD_TYPES_COMPLETE = [
    # Advanced Nomen (Nouns) - 40 examples
    {"sentence": "Die Wissenschaft erforscht neue Erkenntnisse.", "word": "Wissenschaft", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Das Experiment war erfolgreich.", "word": "Experiment", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die Forschung dauert Jahre.", "word": "Forschung", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Eine große Entdeckung wurde gemacht.", "word": "Entdeckung", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die Erfindung veränderte alles.", "word": "Erfindung", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Moderne Technologie hilft uns.", "word": "Technologie", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Der Computer rechnet schnell.", "word": "Computer", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Das Internet verbindet Menschen.", "word": "Internet", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Das Programm läuft fehlerfrei.", "word": "Programm", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die Software wurde aktualisiert.", "word": "Software", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die Hardware ist veraltet.", "word": "Hardware", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Der Roboter arbeitet präzise.", "word": "Roboter", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die Maschine produziert Teile.", "word": "Maschine", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Das Werkzeug ist scharf.", "word": "Werkzeug", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Das Instrument misst genau.", "word": "Instrument", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Das Gerät funktioniert gut.", "word": "Gerät", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Grüne Energie wird wichtiger.", "word": "Energie", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Elektrizität fließt durch Kabel.", "word": "Elektrizität", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die Batterie ist leer.", "word": "Batterie", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Der Motor läuft ruhig.", "word": "Motor", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Das Fahrzeug ist umweltfreundlich.", "word": "Fahrzeug", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Der Verkehr ist stark.", "word": "Verkehr", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Der Transport ist effizient.", "word": "Transport", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die Navigation funktioniert.", "word": "Navigation", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die Kommunikation ist wichtig.", "word": "Kommunikation", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Wichtige Information wird geteilt.", "word": "Information", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Gute Bildung ist wertvoll.", "word": "Bildung", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die Erziehung prägt Kinder.", "word": "Erziehung", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die Universität ist groß.", "word": "Universität", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Das Gymnasium bereitet vor.", "word": "Gymnasium", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die Bibliothek ist ruhig.", "word": "Bibliothek", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Das Museum zeigt Geschichte.", "word": "Museum", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Das Theater spielt Stücke.", "word": "Theater", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Das Konzert war wunderbar.", "word": "Konzert", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Das Orchester spielt Musik.", "word": "Orchester", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Der Dirigent leitet das Orchester.", "word": "Dirigent", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Der Komponist schreibt Musik.", "word": "Komponist", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Der Sänger hat eine schöne Stimme.", "word": "Sänger", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Der Musiker übt täglich.", "word": "Musiker", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Der Künstler malt Bilder.", "word": "Künstler", "type": "Nomen", "options": ["Nomen", "Verb", "Adjektiv"]},

    # Advanced Verben (Verbs) - 40 examples  
    {"sentence": "Die Wissenschaftler erforschen neue Gebiete.", "word": "erforschen", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Sie experimentieren mit neuen Methoden.", "word": "experimentieren", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die Forscher analysieren die Daten.", "word": "analysieren", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Sie entdecken neue Fakten.", "word": "entdecken", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Ingenieure entwickeln Lösungen.", "word": "entwickeln", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Sie konstruieren neue Maschinen.", "word": "konstruieren", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Techniker installieren Geräte.", "word": "installieren", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Programmierer programmieren Software.", "word": "programmieren", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Sie optimieren die Prozesse.", "word": "optimieren", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Experten modernisieren Systeme.", "word": "modernisieren", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Sie digitalisieren alte Dokumente.", "word": "digitalisieren", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Roboter automatisieren Arbeitsprozesse.", "word": "automatisieren", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Sie koordinieren verschiedene Projekte.", "word": "koordinieren", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Manager organisieren Termine.", "word": "organisieren", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Sie planen strategisch.", "word": "planen", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Teams kommunizieren effektiv.", "word": "kommunizieren", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Sie kooperieren miteinander.", "word": "kooperieren", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Mitarbeiter kollaborieren an Projekten.", "word": "kollaborieren", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Sie diskutieren verschiedene Ansätze.", "word": "diskutieren", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Experten evaluieren Ergebnisse.", "word": "evaluieren", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Sie präsentieren ihre Findings.", "word": "präsentieren", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Forscher dokumentieren Prozesse.", "word": "dokumentieren", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Sie implementieren neue Strategien.", "word": "implementieren", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Teams realisieren Visionen.", "word": "realisieren", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Sie transformieren Unternehmen.", "word": "transformieren", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Innovatoren revolutionieren Branchen.", "word": "revolutionieren", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Sie visualisieren komplexe Daten.", "word": "visualisieren", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Algorithmen berechnen Ergebnisse.", "word": "berechnen", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Systeme generieren Reports.", "word": "generieren", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Programme simulieren Szenarien.", "word": "simulieren", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Sie konfigurieren die Einstellungen.", "word": "konfigurieren", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Administratoren synchronisieren Daten.", "word": "synchronisieren", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Sie validieren die Eingaben.", "word": "validieren", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Systeme authentifizieren Benutzer.", "word": "authentifizieren", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Sie verschlüsseln sensitive Daten.", "word": "verschlüsseln", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Firewalls blockieren Angriffe.", "word": "blockieren", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Sie überwachen die Systeme.", "word": "überwachen", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Experten diagnostizieren Probleme.", "word": "diagnostizieren", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Sie reparieren defekte Komponenten.", "word": "reparieren", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Techniker kalibrieren Instrumente.", "word": "kalibrieren", "type": "Verb", "options": ["Nomen", "Verb", "Adjektiv"]},

    # Advanced Adjektive (Adjectives) - 40 examples
    {"sentence": "Ein wissenschaftlicher Durchbruch wurde erzielt.", "word": "wissenschaftlicher", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Die experimentelle Phase beginnt.", "word": "experimentelle", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Innovative Lösungen sind gefragt.", "word": "innovative", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Technologische Fortschritte sind wichtig.", "word": "technologische", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Digitale Transformation verändert alles.", "word": "digitale", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Automatisierte Prozesse sparen Zeit.", "word": "automatisierte", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Intelligente Systeme lernen selbst.", "word": "intelligente", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Komplexe Algorithmen berechnen Lösungen.", "word": "komplexe", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Präzise Messungen sind erforderlich.", "word": "präzise", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Effiziente Methoden werden bevorzugt.", "word": "effiziente", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Nachhaltige Entwicklung ist wichtig.", "word": "nachhaltige", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Umweltfreundliche Technologien werden gefördert.", "word": "umweltfreundliche", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Erneuerbare Energien sind die Zukunft.", "word": "erneuerbare", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Optimale Bedingungen werden geschaffen.", "word": "optimale", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Strategische Planung ist entscheidend.", "word": "strategische", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Systematische Ansätze führen zum Erfolg.", "word": "systematische", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Methodische Vorgehensweisen sind wichtig.", "word": "methodische", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Strukturierte Daten sind wertvoll.", "word": "strukturierte", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Organisierte Teams arbeiten effektiver.", "word": "organisierte", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Koordinierte Aktionen bringen Erfolg.", "word": "koordinierte", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Integrierte Lösungen sind gefragt.", "word": "integrierte", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Interdisziplinäre Zusammenarbeit ist wichtig.", "word": "interdisziplinäre", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Internationale Kooperationen entstehen.", "word": "internationale", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Globale Herausforderungen brauchen Lösungen.", "word": "globale", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Universelle Prinzipien gelten überall.", "word": "universelle", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Fundamentale Erkenntnisse verändern alles.", "word": "fundamentale", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Grundlegende Prinzipien werden angewandt.", "word": "grundlegende", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Wesentliche Faktoren beeinflussen Ergebnisse.", "word": "wesentliche", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Kritische Punkte werden identifiziert.", "word": "kritische", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Entscheidende Momente erfordern Aufmerksamkeit.", "word": "entscheidende", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Bedeutende Fortschritte werden gemacht.", "word": "bedeutende", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Relevante Informationen werden gesammelt.", "word": "relevante", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Signifikante Unterschiede werden festgestellt.", "word": "signifikante", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Erhebliche Verbesserungen sind sichtbar.", "word": "erhebliche", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Beträchtliche Ressourcen werden investiert.", "word": "beträchtliche", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Umfangreiche Studien werden durchgeführt.", "word": "umfangreiche", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Detaillierte Analysen werden erstellt.", "word": "detaillierte", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Genaue Messungen sind erforderlich.", "word": "genaue", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Exakte Berechnungen werden durchgeführt.", "word": "exakte", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]},
    {"sentence": "Korrekte Ergebnisse sind wichtig.", "word": "korrekte", "type": "Adjektiv", "options": ["Nomen", "Verb", "Adjektiv"]}
]

# Grade 3 Fill-Blank Examples - Complete (150 examples)
GRADE3_FILL_BLANK_COMPLETE = [
    # Academic and Scientific contexts (50 examples)
    {"text": "Die ___ erforscht neue Erkenntnisse.", "answer": "Wissenschaft", "options": ["Wissenschaft", "Kunst", "Musik"]},
    {"text": "Das ___ war sehr erfolgreich.", "answer": "Experiment", "options": ["Experiment", "Spiel", "Fest"]},
    {"text": "Die ___ dauert mehrere Jahre.", "answer": "Forschung", "options": ["Forschung", "Ferien", "Party"]},
    {"text": "Eine wichtige ___ wurde gemacht.", "answer": "Entdeckung", "options": ["Entdeckung", "Torte", "Reise"]},
    {"text": "Die ___ veränderte die Welt.", "answer": "Erfindung", "options": ["Erfindung", "Geschichte", "Musik"]},
    {"text": "Moderne ___ hilft den Menschen.", "answer": "Technologie", "options": ["Technologie", "Kleidung", "Nahrung"]},
    {"text": "Der ___ rechnet sehr schnell.", "answer": "Computer", "options": ["Computer", "Taschenrechner", "Abakus"]},
    {"text": "Das ___ verbindet die Welt.", "answer": "Internet", "options": ["Internet", "Telefon", "Radio"]},
    {"text": "Das ___ läuft ohne Fehler.", "answer": "Programm", "options": ["Programm", "Theater", "Konzert"]},
    {"text": "Die ___ wurde aktualisiert.", "answer": "Software", "options": ["Software", "Hardware", "Firmware"]},
    {"text": "Die ___ des Computers ist alt.", "answer": "Hardware", "options": ["Hardware", "Software", "Malware"]},
    {"text": "Der ___ arbeitet sehr präzise.", "answer": "Roboter", "options": ["Roboter", "Mensch", "Tier"]},
    {"text": "Die ___ produziert Autos.", "answer": "Maschine", "options": ["Maschine", "Fabrik", "Werkstatt"]},
    {"text": "Das ___ ist sehr scharf.", "answer": "Werkzeug", "options": ["Werkzeug", "Messer", "Säge"]},
    {"text": "Das ___ misst die Temperatur.", "answer": "Instrument", "options": ["Instrument", "Thermometer", "Barometer"]},
    {"text": "Das elektronische ___ funktioniert gut.", "answer": "Gerät", "options": ["Gerät", "Spielzeug", "Buch"]},
    {"text": "Saubere ___ ist wichtig für die Umwelt.", "answer": "Energie", "options": ["Energie", "Luft", "Erde"]},
    {"text": "___ fließt durch die Leitungen.", "answer": "Elektrizität", "options": ["Elektrizität", "Wasser", "Gas"]},
    {"text": "Die ___ des Handys ist leer.", "answer": "Batterie", "options": ["Batterie", "Tasche", "Hülle"]},
    {"text": "Der ___ des Autos läuft ruhig.", "answer": "Motor", "options": ["Motor", "Reifen", "Lenkrad"]},
    {"text": "Das umweltfreundliche ___ fährt elektrisch.", "answer": "Fahrzeug", "options": ["Fahrzeug", "Fahrrad", "Auto"]},
    {"text": "Der ___ in der Stadt ist sehr stark.", "answer": "Verkehr", "options": ["Verkehr", "Wind", "Regen"]},
    {"text": "Der ___ der Waren erfolgt per LKW.", "answer": "Transport", "options": ["Transport", "Verkauf", "Kauf"]},
    {"text": "Die ___ im Auto zeigt den Weg.", "answer": "Navigation", "options": ["Navigation", "Karte", "Kompass"]},
    {"text": "Gute ___ ist sehr wichtig.", "answer": "Kommunikation", "options": ["Kommunikation", "Isolation", "Meditation"]},
    {"text": "Wichtige ___ wird geteilt.", "answer": "Information", "options": ["Information", "Geheimnis", "Lüge"]},
    {"text": "Eine gute ___ öffnet viele Türen.", "answer": "Bildung", "options": ["Bildung", "Unterhaltung", "Ablenkung"]},
    {"text": "Die ___ der Kinder ist wichtig.", "answer": "Erziehung", "options": ["Erziehung", "Vernachlässigung", "Verwöhnung"]},
    {"text": "Die ___ hat viele Fakultäten.", "answer": "Universität", "options": ["Universität", "Grundschule", "Kindergarten"]},
    {"text": "Das ___ bereitet auf das Studium vor.", "answer": "Gymnasium", "options": ["Gymnasium", "Spielplatz", "Kino"]},
    {"text": "In der ___ gibt es viele Bücher.", "answer": "Bibliothek", "options": ["Bibliothek", "Bäckerei", "Bank"]},
    {"text": "Das ___ zeigt alte Kunstwerke.", "answer": "Museum", "options": ["Museum", "Restaurant", "Hotel"]},
    {"text": "Im ___ werden Dramen aufgeführt.", "answer": "Theater", "options": ["Theater", "Kino", "Zirkus"]},
    {"text": "Das ___ war wunderschön.", "answer": "Konzert", "options": ["Konzert", "Gewitter", "Chaos"]},
    {"text": "Das ___ spielt klassische Musik.", "answer": "Orchester", "options": ["Orchester", "Radio", "Fernseher"]},
    {"text": "Der ___ leitet das Orchester.", "answer": "Dirigent", "options": ["Dirigent", "Sänger", "Pianist"]},
    {"text": "Der ___ schreibt wunderschöne Musik.", "answer": "Komponist", "options": ["Komponist", "Maler", "Dichter"]},
    {"text": "Der ___ hat eine wundervolle Stimme.", "answer": "Sänger", "options": ["Sänger", "Sprecher", "Schauspieler"]},
    {"text": "Der ___ übt täglich sein Instrument.", "answer": "Musiker", "options": ["Musiker", "Sportler", "Koch"]},
    {"text": "Der ___ malt abstrakte Bilder.", "answer": "Künstler", "options": ["Künstler", "Handwerker", "Verkäufer"]},
    {"text": "Der ___ erschafft Gemälde.", "answer": "Maler", "options": ["Maler", "Fotograf", "Bildhauer"]},
    {"text": "Der ___ formt Skulpturen aus Stein.", "answer": "Bildhauer", "options": ["Bildhauer", "Maler", "Fotograf"]},
    {"text": "Der ___ entwirft Gebäude.", "answer": "Architekt", "options": ["Architekt", "Bauarbeiter", "Hausmeister"]},
    {"text": "Der ___ gestaltet Webseiten.", "answer": "Designer", "options": ["Designer", "Programmierer", "Verkäufer"]},
    {"text": "Der ___ entwickelt neue Maschinen.", "answer": "Ingenieur", "options": ["Ingenieur", "Mechaniker", "Arbeiter"]},
    {"text": "Der ___ forscht an der Universität.", "answer": "Wissenschaftler", "options": ["Wissenschaftler", "Student", "Hausmeister"]},
    {"text": "Der ___ hält Vorlesungen.", "answer": "Professor", "options": ["Professor", "Student", "Sekretär"]},
    {"text": "Der ___ behandelt kranke Menschen.", "answer": "Doktor", "options": ["Doktor", "Patient", "Krankenpfleger"]},
    {"text": "Der ___ ist Experte für Herzchirurgie.", "answer": "Spezialist", "options": ["Spezialist", "Anfänger", "Laie"]},
    {"text": "Der ___ kennt sich sehr gut aus.", "answer": "Experte", "options": ["Experte", "Anfänger", "Laie"]},

    # Technology and Modern Life (50 examples)
    {"text": "Die ___ verändert unsere Arbeitswelt.", "answer": "Digitalisierung", "options": ["Digitalisierung", "Handarbeit", "Tradition"]},
    {"text": "Die ___ macht Arbeit effizienter.", "answer": "Automatisierung", "options": ["Automatisierung", "Handarbeit", "Verzögerung"]},
    {"text": "Die ___ ersetzt menschliche Arbeit.", "answer": "Robotisierung", "options": ["Robotisierung", "Humanisierung", "Personalisierung"]},
    {"text": "___ hilft bei komplexen Problemen.", "answer": "Künstliche Intelligenz", "options": ["Künstliche Intelligenz", "Menschliche Dummheit", "Natürliche Instinkte"]},
    {"text": "Der ___ berechnet die Lösung.", "answer": "Algorithmus", "options": ["Algorithmus", "Mensch", "Zufall"]},
    {"text": "Die ___ erfordert logisches Denken.", "answer": "Programmierung", "options": ["Programmierung", "Improvisation", "Fantasie"]},
    {"text": "Die ___ ist ein kreativer Prozess.", "answer": "Softwareentwicklung", "options": ["Softwareentwicklung", "Hardwareproduktion", "Massenproduktion"]},
    {"text": "Die ___ speichert große Datenmengen.", "answer": "Datenbank", "options": ["Datenbank", "Bibliothek", "Archiv"]},
    {"text": "Der ___ schützt persönliche Informationen.", "answer": "Datenschutz", "options": ["Datenschutz", "Datenverlust", "Datendiebstahl"]},
    {"text": "Die ___ wird immer wichtiger.", "answer": "Cybersicherheit", "options": ["Cybersicherheit", "Sorglosigkeit", "Leichtsinn"]},
    {"text": "Die ___ schützt sensible Daten.", "answer": "Verschlüsselung", "options": ["Verschlüsselung", "Offenlegung", "Preisgabe"]},
    {"text": "Die ___ bestätigt die Identität.", "answer": "Authentifizierung", "options": ["Authentifizierung", "Verschleierung", "Tarnung"]},
    {"text": "Ein sicheres ___ schützt das Konto.", "answer": "Passwort", "options": ["Passwort", "Geburtsdatum", "Name"]},
    {"text": "Der ___ identifiziert den Nutzer.", "answer": "Benutzername", "options": ["Benutzername", "Nickname", "Spitzname"]},
    {"text": "Die ___ erfolgt über das System.", "answer": "Anmeldung", "options": ["Anmeldung", "Abmeldung", "Verweigerung"]},
    {"text": "Die ___ ist für neue Nutzer erforderlich.", "answer": "Registrierung", "options": ["Registrierung", "Löschung", "Ignorierung"]},
    {"text": "Das persönliche ___ enthält alle Daten.", "answer": "Konto", "options": ["Konto", "Geheimnis", "Problem"]},
    {"text": "Das ___ zeigt persönliche Informationen.", "answer": "Profil", "options": ["Profil", "Geheimnis", "Rätsel"]},
    {"text": "Die ___ können angepasst werden.", "answer": "Einstellungen", "options": ["Einstellungen", "Probleme", "Geheimnisse"]},
    {"text": "Die ___ bestimmt das Systemverhalten.", "answer": "Konfiguration", "options": ["Konfiguration", "Zerstörung", "Verwirrung"]},
    {"text": "Die ___ erfolgt automatisch.", "answer": "Installation", "options": ["Installation", "Deinstallation", "Zerstörung"]},
    {"text": "Das ___ verbessert die Software.", "answer": "Update", "options": ["Update", "Downgrade", "Stillstand"]},
    {"text": "Das ___ bietet neue Funktionen.", "answer": "Upgrade", "options": ["Upgrade", "Downgrade", "Rückschritt"]},
    {"text": "Der ___ lädt Dateien herunter.", "answer": "Download", "options": ["Download", "Upload", "Stillstand"]},
    {"text": "Der ___ lädt Dateien hoch.", "answer": "Upload", "options": ["Upload", "Download", "Stillstand"]},
    {"text": "Das ___ sichert wichtige Daten.", "answer": "Backup", "options": ["Backup", "Löschung", "Verlust"]},
    {"text": "Die ___ stellt Daten wieder her.", "answer": "Wiederherstellung", "options": ["Wiederherstellung", "Zerstörung", "Verlust"]},
    {"text": "Die ___ gleicht Daten ab.", "answer": "Synchronisation", "options": ["Synchronisation", "Verwirrung", "Chaos"]},
    {"text": "Das ___ speichert Daten online.", "answer": "Cloud-Computing", "options": ["Cloud-Computing", "Local-Storage", "Paper-Archive"]},
    {"text": "Der ___ wird knapp.", "answer": "Speicherplatz", "options": ["Speicherplatz", "Bildschirm", "Lautsprecher"]},
    {"text": "Die ___ speichert alle Programme.", "answer": "Festplatte", "options": ["Festplatte", "Tastatur", "Maus"]},
    {"text": "Der ___ wird für Programme benötigt.", "answer": "Arbeitsspeicher", "options": ["Arbeitsspeicher", "Bildschirm", "Tastatur"]},
    {"text": "Der ___ berechnet alle Operationen.", "answer": "Prozessor", "options": ["Prozessor", "Monitor", "Drucker"]},
    {"text": "Die ___ erzeugt die Bilder.", "answer": "Grafikkarte", "options": ["Grafikkarte", "Soundkarte", "Netzwerkkarte"]},
    {"text": "Das ___ verbindet alle Komponenten.", "answer": "Motherboard", "options": ["Motherboard", "Keyboard", "Dashboard"]},
    {"text": "Die ___ ermöglicht Internetverbindung.", "answer": "Netzwerkkarte", "options": ["Netzwerkkarte", "Grafikkarte", "Soundkarte"]},
    {"text": "Der ___ leitet Daten weiter.", "answer": "Router", "options": ["Router", "Monitor", "Drucker"]},
    {"text": "Das ___ stellt Internetverbindung her.", "answer": "Modem", "options": ["Modem", "Radio", "Fernseher"]},
    {"text": "Das ___ überträgt Strom und Daten.", "answer": "Kabel", "options": ["Kabel", "Seil", "Kette"]},
    {"text": "Die ___ Übertragung funktioniert ohne Kabel.", "answer": "Wireless", "options": ["Wireless", "Wired", "Cable"]},
    {"text": "___ verbindet Geräte miteinander.", "answer": "Bluetooth", "options": ["Bluetooth", "Redtooth", "Greentooth"]},
    {"text": "Das ___ ermöglicht kabelloses Internet.", "answer": "WLAN", "options": ["WLAN", "LAN", "WAN"]},
    {"text": "Der ___ bietet öffentliches Internet.", "answer": "Hotspot", "options": ["Hotspot", "Coldspot", "Nospot"]},
    {"text": "Die ___ bestimmt die Internetgeschwindigkeit.", "answer": "Bandbreite", "options": ["Bandbreite", "Länge", "Höhe"]},
    {"text": "Eine niedrige ___ verlangsamt die Verbindung.", "answer": "Latenz", "options": ["Latenz", "Frequenz", "Konstanz"]},
    {"text": "Das ___ zeigt Videos in Echtzeit.", "answer": "Streaming", "options": ["Streaming", "Downloading", "Uploading"]},
    {"text": "Das ___ zeigt bewegte Bilder.", "answer": "Video", "options": ["Video", "Audio", "Text"]},
    {"text": "Das ___ überträgt Klänge.", "answer": "Audio", "options": ["Audio", "Video", "Text"]},
    {"text": "___ kombiniert verschiedene Medien.", "answer": "Multimedia", "options": ["Multimedia", "Monomedia", "Nullmedia"]},
    {"text": "Die ___ erweckt Bilder zum Leben.", "answer": "Animation", "options": ["Animation", "Stagnation", "Stillstand"]},

    # Advanced concepts and future (50 examples)
    {"text": "Die ___ bildet die Realität nach.", "answer": "Simulation", "options": ["Simulation", "Realität", "Fantasie"]},
    {"text": "___ erschafft künstliche Welten.", "answer": "Virtual Reality", "options": ["Virtual Reality", "Real Life", "Dream World"]},
    {"text": "___ erweitert die Realität.", "answer": "Augmented Reality", "options": ["Augmented Reality", "Reduced Reality", "Simple Reality"]},
    {"text": "Das ___ zeigt dreidimensionale Bilder.", "answer": "Hologramm", "options": ["Hologramm", "Foto", "Gemälde"]},
    {"text": "Der ___ erstellt Objekte schichtweise.", "answer": "3D-Druck", "options": ["3D-Druck", "2D-Druck", "Handdruck"]},
    {"text": "Der ___ testet neue Ideen.", "answer": "Prototyp", "options": ["Prototyp", "Original", "Kopie"]},
    {"text": "Die ___ bringt Neuerungen hervor.", "answer": "Innovation", "options": ["Innovation", "Stagnation", "Tradition"]},
    {"text": "Die ___ schreitet schnell voran.", "answer": "Entwicklung", "options": ["Entwicklung", "Stillstand", "Rückschritt"]},
    {"text": "Der technologische ___ ist rasant.", "answer": "Fortschritt", "options": ["Fortschritt", "Rückschritt", "Stillstand"]},
    {"text": "Die digitale ___ verändert alles.", "answer": "Revolution", "options": ["Revolution", "Stagnation", "Tradition"]},
    {"text": "Die ___ geschieht langsam aber stetig.", "answer": "Evolution", "options": ["Evolution", "Revolution", "Devolution"]},
    {"text": "Die ___ der Gesellschaft ist notwendig.", "answer": "Transformation", "options": ["Transformation", "Stagnation", "Regression"]},
    {"text": "Die ___ alter Systeme ist wichtig.", "answer": "Modernisierung", "options": ["Modernisierung", "Verschlechterung", "Alterung"]},
    {"text": "Die ___ der Prozesse spart Zeit.", "answer": "Optimierung", "options": ["Optimierung", "Verschlechterung", "Komplizierung"]},
    {"text": "Die ___ der Qualität ist sichtbar.", "answer": "Verbesserung", "options": ["Verbesserung", "Verschlechterung", "Gleichstand"]},
    {"text": "Die ___ wird immer wichtiger.", "answer": "Effizienz", "options": ["Effizienz", "Ineffizienz", "Verschwendung"]},
    {"text": "Die ___ steigt durch Automatisierung.", "answer": "Produktivität", "options": ["Produktivität", "Faulheit", "Stillstand"]},
    {"text": "Die ___ des Systems ist beeindruckend.", "answer": "Leistungsfähigkeit", "options": ["Leistungsfähigkeit", "Schwäche", "Unfähigkeit"]},
    {"text": "Die ___ wird voll ausgeschöpft.", "answer": "Kapazität", "options": ["Kapazität", "Leere", "Mangel"]},
    {"text": "Das ___ ist noch nicht ausgeschöpft.", "answer": "Potenzial", "options": ["Potenzial", "Problem", "Hindernis"]},
    {"text": "Neue ___ eröffnen sich täglich.", "answer": "Möglichkeit", "options": ["Möglichkeit", "Unmöglichkeit", "Beschränkung"]},
    {"text": "Eine große ___ bietet sich.", "answer": "Gelegenheit", "options": ["Gelegenheit", "Hindernis", "Blockade"]},
    {"text": "Die ___ sollte genutzt werden.", "answer": "Chance", "options": ["Chance", "Gefahr", "Bedrohung"]},
    {"text": "Das ___ muss bewertet werden.", "answer": "Risiko", "options": ["Risiko", "Sicherheit", "Gewissheit"]},
    {"text": "Die ___ wurde erkannt.", "answer": "Gefahr", "options": ["Gefahr", "Sicherheit", "Chance"]},
    {"text": "Die ___ ist real.", "answer": "Bedrohung", "options": ["Bedrohung", "Hilfe", "Unterstützung"]},
    {"text": "Die ___ wird gewährleistet.", "answer": "Sicherheit", "options": ["Sicherheit", "Gefahr", "Unsicherheit"]},
    {"text": "Der ___ wird verstärkt.", "answer": "Schutz", "options": ["Schutz", "Angriff", "Schaden"]},
    {"text": "Die ___ wird organisiert.", "answer": "Verteidigung", "options": ["Verteidigung", "Angriff", "Kapitulation"]},
    {"text": "Der ___ wird geleistet.", "answer": "Widerstand", "options": ["Widerstand", "Gehorsam", "Unterwerfung"]},
    {"text": "Die ___ formiert sich.", "answer": "Opposition", "options": ["Opposition", "Zustimmung", "Unterstützung"]},
    {"text": "Der ___ wird laut.", "answer": "Protest", "options": ["Protest", "Beifall", "Zustimmung"]},
    {"text": "Die ___ findet statt.", "answer": "Demonstration", "options": ["Demonstration", "Versteckung", "Verheimlichung"]},
    {"text": "Die soziale ___ wächst.", "answer": "Bewegung", "options": ["Bewegung", "Stillstand", "Lähmung"]},
    {"text": "Die ___ läuft erfolgreich.", "answer": "Kampagne", "options": ["Kampagne", "Niederlage", "Aufgabe"]},
    {"text": "Die ___ wird gestartet.", "answer": "Initiative", "options": ["Initiative", "Passivität", "Untätigkeit"]},
    {"text": "Das ___ wird umgesetzt.", "answer": "Projekt", "options": ["Projekt", "Problem", "Hindernis"]},
    {"text": "Der ___ wird entwickelt.", "answer": "Plan", "options": ["Plan", "Chaos", "Zufall"]},
    {"text": "Die ___ wird ausgearbeitet.", "answer": "Strategie", "options": ["Strategie", "Improvisation", "Planlosigkeit"]},
    {"text": "Die ___ wird angewandt.", "answer": "Taktik", "options": ["Taktik", "Naivität", "Ungeschicklichkeit"]},
    {"text": "Die ___ wird verbessert.", "answer": "Methode", "options": ["Methode", "Chaos", "Willkür"]},
    {"text": "Das ___ wird optimiert.", "answer": "Verfahren", "options": ["Verfahren", "Problem", "Hindernis"]},
    {"text": "Der ___ wird beschleunigt.", "answer": "Prozess", "options": ["Prozess", "Stillstand", "Rückschritt"]},
    {"text": "Der ___ wird geändert.", "answer": "Ablauf", "options": ["Ablauf", "Stillstand", "Blockade"]},
    {"text": "Die ___ wird beachtet.", "answer": "Reihenfolge", "options": ["Reihenfolge", "Chaos", "Willkür"]},
    {"text": "Die ___ wird programmiert.", "answer": "Sequenz", "options": ["Sequenz", "Zufall", "Chaos"]},
    {"text": "Die ___ wird fortgesetzt.", "answer": "Serie", "options": ["Serie", "Ende", "Unterbrechung"]},
    {"text": "Die ___ wird geschmiedet.", "answer": "Kette", "options": ["Kette", "Bruch", "Trennung"]},
    {"text": "Die ___ wird hergestellt.", "answer": "Verbindung", "options": ["Verbindung", "Trennung", "Isolation"]},
    {"text": "Der ___ wird erklärt.", "answer": "Zusammenhang", "options": ["Zusammenhang", "Widerspruch", "Gegensatz"]}
]